export const meta = {
  name: 'blitz',
  description: 'Product-first parallel build: one skeleton agent makes modules collision-free, then whole modules are built in parallel worktrees by full-stack agents, merged, booted and fixed. Two waves. No PM/designer/reviewer ceremony; hardening is a separate pass.',
  whenToUse: 'Run when the foundation exists and the product must appear fast. args: {ts, wave: 1|2|"all"}.',
  phases: [
    { title: 'Skeleton', detail: 'auto-discovered modules, migration/seed/i18n conventions, auth+department context, MODULE-GUIDE.md' },
    { title: 'Wave 1', detail: 'accounts+departments, structure, work+projects, events, personal, inbox+telegram — in parallel worktrees' },
    { title: 'Merge 1', detail: 'merge branches, resolve conflicts, fast gates' },
    { title: 'Integrate 1', detail: 'boot with --demo, click through, fix runtime errors' },
    { title: 'Wave 2', detail: 'analytics+pages, AI helpers, super admin console + switches' },
    { title: 'Merge 2', detail: 'merge, gates' },
    { title: 'Integrate 2', detail: 'boot, click through every module, fix, commit' },
  ],
}

const TS = (args && args.ts) || 'unstamped'
const WAVE = (args && args.wave) || 'all'
const ROOT = 'C:/Users/rpwal/Documents/Work/eGov/WorkPortal'

const CTX = `You are building Devon (WorkPortal), a self-hosted department work-tracking platform. Binding documents in the repo: docs/03-plan/TECH-SPEC.md (architecture, data model §3, API §4, frontend §5, backend §6, Telegram §7, AI §8, analytics §9, admin §10, pause/wipe §11, demo §14, coding standards §16, decisions §19), DESIGN.md (tokens, type, motion, components, states, copy rules), docs/03-plan/FEATURE-PLAN.md (product intent and refusals), MODULE-GUIDE.md (how modules plug in without touching shared files — read it first if it exists), packages/i18n/TERMS.md (terminology). The foundation already exists: pnpm monorepo (apps/api Fastify 5, apps/web Vite+React 19, packages/db Drizzle+Postgres with RLS and an immutable audit chain, packages/contracts, packages/ui tokens/components, packages/i18n with four locales uz-Latn/uz-Cyrl/ru/en, e2e Playwright, infra Compose). Read the existing code before adding to it and follow its conventions exactly.
RULES: build real, working, polished software, not stubs. Every string through i18n in all four locales (add keys in your module's message files). Every screen has empty/loading/error states. Tokens only, no raw colours. Every department table has department_id and an RLS policy; personal-workspace tables are owner-only. Every write appends an audit event (use the existing helper). Server-side validation with Zod on every route. No secrets. No query in a loop. Commit early and often on your branch with messages "<module>: <what a user can now do>". Before finishing run: node agentic/scripts/gate.mjs --profile fast (typecheck, lint, unit, i18n, secrets) and make it green; if a gate is red because of code outside your module, fix the root cause anyway and say so. Also extend the demo seed for your module so the demo is rich and realistic (Uzbek three-part names, believable data, dates around 2026-09).
If you are in a git worktree: first run "pnpm install --prefer-offline" so node_modules exist, then work only inside your module's paths listed in your task plus your module's message and seed files; never edit another module's folder. Report your branch name (git rev-parse --abbrev-ref HEAD) in the result.`

const DONE = { type: 'object', properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, branch: { type: 'string' }, commits: { type: 'number' }, summary: { type: 'string' }, routes: { type: 'array', items: { type: 'string' } }, gates_green: { type: 'boolean' }, notes: { type: 'string' } }, required: ['status', 'summary'] }
const mk = (label, phase, prompt, extra) => agent(`${CTX}\n\n${prompt}`, { label, phase, agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: DONE, ...(extra || {}) })

// ---------- Phase: Skeleton ----------
let skeleton = null
if (!(args && args.skipSkeleton) && (WAVE === 'all' || WAVE === 1 || WAVE === '1')) {
  phase('Skeleton')
  skeleton = await mk('skeleton', 'Skeleton', `TASK: make the codebase safe for several agents to add whole modules IN PARALLEL without editing the same files. Implement and commit on the current branch (master):
1) API module auto-discovery: apps/api/src/modules/<name>/index.ts exports a Fastify plugin; a loader in apps/api (fs.readdir at boot, deterministic order, dynamic import) registers every module under /api/v1 with its own prefix; each module owns its routes, services, repos, jobs and Zod schemas. Convert any existing hand-registered module to the loader.
2) DB: Drizzle schema per module in packages/db/src/schema/<module>.ts (modules import their own tables; do not require a central schema index edit); migrations are plain SQL files in packages/db/migrations applied in filename order with a _migrations tracking table (keep/adapt the existing migrator; make it idempotent and journal-free); reserve prefixes: 0100_ accounts-departments, 0200_ structure, 0300_ work, 0400_ events, 0500_ personal, 0600_ notifications, 0700_ analytics-pages, 0800_ ai, 0900_ admin. Seeds: packages/db/src/seed/modules/<module>.ts auto-discovered, each exporting { order, seed(ctx) }; the demo seed runs them in order; make the existing seed a module.
3) i18n: per-module message files packages/i18n/messages/modules/<module>/{uz-Latn,uz-Cyrl,ru,en}.json merged into the four catalogues by a build step (add a script and wire it into the i18n package build, dev and the check-i18n config) so modules never edit the shared catalogues.
4) Web: feature auto-discovery — apps/web/src/features/<name>/manifest.ts(x) (via import.meta.glob) declaring routes (path, lazy component, title key, icon), sidebar entries, and command-palette entries; the shell reads all manifests; keep the existing shell and route mechanism but make new features droppable without editing shared files. Provide a typed API client helper and the useSession()/useDepartment() hooks (current user, memberships, current department id with a switcher stub) backed by the existing sessions/departments code; if no login screen exists yet, add a minimal working one (login/logout) so every module can be tested with the demo accounts.
5) Domain events: a tiny bus in the API (emit(type, payload) writing to an outbox table in the same transaction; a worker drains it) that later modules subscribe to; document the event names convention.
6) Write MODULE-GUIDE.md at the repo root: exact folder conventions, how to add routes/tables/migrations/seeds/messages/features, the auth and department helpers, the audit helper, the event bus, how to run the app with --demo, and the fast-gate command. Keep it precise and short.
7) Prove it: pnpm start --demo boots (start Docker Desktop if needed: start "" "C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe" then wait until docker ps works; if Docker cannot run, say so in notes and verify statically), the login works with a demo account, fast gates are green. Commit everything on master. Return branch "master".`)
  log(`skeleton: ${skeleton ? skeleton.status : 'died'} — ${skeleton ? skeleton.summary.slice(0, 200) : ''}`)
  if (!skeleton || skeleton.status === 'BLOCKED') throw new Error('skeleton blocked: ' + (skeleton && skeleton.notes))
}

// ---------- Wave 1 ----------
const wave1 = [
  { key: 'accounts-departments', prompt: `MODULE accounts-departments (TECH-SPEC §2.1, §2.2, §2.3, §3.1; TASKS.md EPIC-001 and EPIC-002). Deliver, working end to end with polished UI: registration (login or email, password policy with argon2id, given/family/optional patronymic, optional photo with upload + WebP variants, optional title, locale), login/logout, sessions with device list and sign-out-everywhere, optional 2FA (TOTP with recovery codes; leave a hook for Telegram codes), profile and settings pages, password reset by super admin (temporary password + forced change), account deletion (soft, 30-day anonymise job), fresh-account landing "Create a department or join one"; department request form (name, description, any number of bo'limlar rows with colours, locale, emoji/colour) → super admin approval queue page (minimal but real: approve/reject with reason) → on approval the department exists, requester is head, join key (12 chars, unambiguous alphabet) is generated and the head sets or accepts a generated join password; Invite sheet with link /join/<key>, password, QR code, "Copy invitation" that copies a localised text in the current locale, rotate key/password, join-approval toggle; join by link (/join/:key with login/register interception, then password) and by form (key + password), rate-limited, uniform error; memberships list, remove member, leave, transfer headship; department settings (allow_self_assign, allow_structure_edit, join_requires_approval, who_can_connect_telegram_group, quiet_hours, locale, colours, deletion request); department switcher in the shell. Demo seed: super admin, 3 departments (one pending request), ~40 users with Uzbek three-part names. Paths: apps/api/src/modules/accounts, apps/api/src/modules/departments, packages/db/src/schema/{accounts,departments}.ts, packages/db/migrations/0100_*.sql, packages/db/src/seed/modules/{accounts,departments}.ts, apps/web/src/features/{accounts,departments}/**, packages/i18n/messages/modules/{accounts,departments}/*.json, plus the shell hooks the guide names.` },
  { key: 'structure', prompt: `MODULE structure (TECH-SPEC §2.3, §3.1 units/unit_roles; TASKS.md EPIC-003). Deliver: bo'limlar with unlimited nesting (ltree or closure), colours, inline rename, drag reorder, delete with undo (members become unassigned); self-assignment to units and unit roles (bo'lim boshlig'i / o'rinbosar / a'zo) gated by the department settings (default allowed) — read the settings shape from MODULE-GUIDE.md / the departments module contract (department_settings jsonb keys allow_self_assign, allow_structure_edit); head can assign others; an org chart view (vendored d3-org-chart or an equivalent SVG tree you write) that renders a department with zero unit heads and one with three levels equally well, keyboard navigable, PNG export; member cards; the People page listing members grouped by unit. Demo seed: one department modelled on "Axborot-tahlil va ijro intizomi boshqarmasi" with two bo'limlar and a sub-bo'lim, one flat department with no unit heads. Paths: apps/api/src/modules/structure, packages/db/src/schema/structure.ts, packages/db/migrations/0200_*.sql, packages/db/src/seed/modules/structure.ts, apps/web/src/features/structure/**, packages/i18n/messages/modules/structure/*.json. Assume users, departments, memberships tables exist from the foundation (check packages/db/src/schema and migrations 0003/0004) and use them; do not redefine them.` },
  { key: 'work', prompt: `MODULE work (TECH-SPEC §3.2, §4 filter grammar, §5 boards; TASKS.md EPIC-004 and EPIC-005). Deliver: cards with giver → assignee (member pickers), title, description (rich text via Tiptap or a solid textarea with markdown for now), priority, start/due with a risk badge, links with title unfurl (SSRF-safe: block private ranges) and attachments (presigned upload if the foundation has MinIO, else local disk adapter behind the same interface), nested checklist, comments with @mentions, activity timeline (Jira-like), labels, watchers, undo archive; the People board: one column per member grouped under colour-coded bo'lim sections (unassigned last), virtualised, drag-and-drop with @atlaskit/pragmatic-drag-and-drop (mouse + keyboard + live-region announcements), fractional order keys; card peek panel and full card page; quick-add bar parsing "Name: title, friday" with rules for uz/ru/en dates and member names; views: table (inline edit), timeline (SVG), calendar (FullCalendar 7 or a clean month grid), "mine"; saved views and a filter grammar parser (assignee:@me giver:@x status:active due:<=friday project:"..." label:x unit:"..." free text) producing SQL predicates, shareable URLs; archive page per person (department-readable, restore); group projects: members, objective (shared) and subjective (per-member) tasks, progress, milestones, project page, project cards in members' columns, one template. Optimistic updates with rollback. Demo seed: ~250 cards across people with givers, links, checklists, comments; 6 projects. Paths: apps/api/src/modules/{work,projects}, packages/db/src/schema/{work,projects}.ts, packages/db/migrations/0300_*.sql, packages/db/src/seed/modules/{work,projects}.ts, apps/web/src/features/{work,projects}/**, packages/i18n/messages/modules/{work,projects}/*.json, packages/contracts/src/filter-grammar.ts (new file).` },
  { key: 'events', prompt: `MODULE events (TECH-SPEC §3.4; TASKS.md EPIC-008). Deliver: events with categories, cover illustration (ship an open-licence vector set recoloured to tokens inside apps/web/src/features/events/illustrations), time/place/place_url, capacity with waitlist, RSVP yes/no/maybe with guests, change and cancel before the deadline, comments, organiser updates with a diff summary and change notifications (emit domain events; the inbox module delivers them), reminders (jobs at 1 day and 1 hour before, configurable), carpooling (driver offers seats + departure point/time; colleagues claim; waitlist when full), polls (date / single / multi, anonymous option, deadline, animated results), "who brings what" items claimable, photos (links) after the event, feedback (rating + comment, anonymous option), calendar view (month/list), ICS export per event and per person, cancel flow notifying RSVPed members, event page that feels delightful (see DESIGN.md motion tokens; restrained). Demo seed: 5 events (one with carpools and a date poll, one cancelled, one done with photos and feedback). Paths: apps/api/src/modules/events, packages/db/src/schema/events.ts, packages/db/migrations/0400_*.sql, packages/db/src/seed/modules/events.ts, apps/web/src/features/events/**, packages/i18n/messages/modules/events/*.json.` },
  { key: 'personal', prompt: `MODULE personal (TECH-SPEC §3.3; TASKS.md EPIC-009). Deliver, strictly private to the owner (owner-only RLS; never visible to heads or admin view-as): sprints (3h / day / week / custom) with a goal and rollover; nested tasks with checkboxes, drag reorder, keyboard; today/focus view; notes; a canvas with Excalidraw (@excalidraw/excalidraw, MIT) plus a sticky-note overlay, autosave and restore; Pomodoro timer (defaults 25/5/15, 4 cycles, editable in settings, sounds, browser notifications, a mini widget in the shell top bar that keeps running across routes, session log and simple stats); linking a personal task to a department card (id only). Demo seed: personal workspaces for the demo accounts with sprints, nested tasks, a canvas and Pomodoro history. Paths: apps/api/src/modules/personal, packages/db/src/schema/personal.ts, packages/db/migrations/0500_*.sql, packages/db/src/seed/modules/personal.ts, apps/web/src/features/personal/**, packages/i18n/messages/modules/personal/*.json.` },
  { key: 'inbox-telegram', prompt: `MODULE inbox-telegram (TECH-SPEC §3.6, §6 jobs, §7; TASKS.md EPIC-006 and EPIC-007). Deliver: notifications model with reasons (assigned, mentioned, due, updated, rsvp, poll, decision, digest, system) fed by the domain-event bus from MODULE-GUIDE.md (subscribe to the event names other modules emit: define a small registry of expected events for cards, comments, events, polls, memberships and handle unknown ones gracefully); inbox drawer + page with mark read/archive; preferences per type and channel (inapp, telegram, email optional); quiet hours (department default 20:00–08:00 + weekends, personal override to quieter); deadline reminders and daily/weekly digests as pg-boss jobs in Asia/Tashkent; ICS feed per person; Telegram bot with grammY (webhook route + a polling fallback for local dev), linking via /start <code> + QR in Settings, localized templates for all four locales, commands /today /mytasks /events /mute, inline buttons for RSVP, poll vote, mark done, snooze; department group connection: add bot to a group, /connect <join key> (allowed per department setting), choose update kinds, group receives events/polls/announcements/weekly summary; "pointer not payload": messages contain titles, dates, deep links only — never contact details (serializer allow-list + unit test); reset/2FA code delivery hook. If a bot token is not configured, the module must run with a no-op transport and show a clear settings hint. Demo seed: notifications for demo accounts, a mock Telegram link. Paths: apps/api/src/modules/{notifications,telegram}, packages/db/src/schema/notifications.ts, packages/db/migrations/0600_*.sql, packages/db/src/seed/modules/notifications.ts, apps/web/src/features/inbox/**, packages/i18n/messages/modules/{inbox,telegram}/*.json.` },
]
const wave2 = [
  { key: 'analytics-pages', prompt: `MODULE analytics-pages (TECH-SPEC §9, §3.5; TASKS.md EPIC-010 and EPIC-011). Deliver: analytics page for every member with a filter bar using the work module's filter grammar (person, unit, project, giver, label, date range, status), saved filters, sections: throughput per week, on-time rate, open vs overdue trend, load per person and per unit, project progress, events participation and RSVP rates, poll turnout, personal stats for the viewer; nightly precomputed aggregates table plus on-write patches so no analytics query exceeds 100 ms; Recharts 3 charts with draw-in animation and NumberFlow tickers, keyboard accessible, CSV/PNG export, pin a chart to Home; a Home page per role answering "due from me / needs my decision / around me" with the pinned charts and upcoming events. Pages: department pages with Tiptap 3 (mentions, checklist items, callouts, versions with diff/restore), a "how we work" template, an onboarding checklist template that becomes a newcomer's personal tasks on join (opt-in per department; hook into the memberships join event). Demo seed: analytics history, 6 pages, one onboarding template. Paths: apps/api/src/modules/{analytics,pages}, packages/db/src/schema/{analytics,pages}.ts, packages/db/migrations/0700_*.sql, seeds, apps/web/src/features/{analytics,pages,home}/**, message files.` },
  { key: 'ai', prompt: `MODULE ai (TECH-SPEC §8; docs/03-plan/integrations/glm-api-instruction.md; TASKS.md EPIC-012). Deliver packages/ai and apps/api/src/modules/ai: gateway to the OpenAI-compatible endpoint https://api-llm.gpu.uz/v1 model glm-5.2 with AI_API_KEY from env (never in repo), max_tokens >= 1024 always (retry with double on empty content + finish_reason length), reasoning_content never shown or stored, tool calls with strict JSON schemas validated by Zod (one retry with the error), history trimming, per-department monthly budget in UZS (19500 per million tokens) with soft cap alert and hard stop, per-call traces (tokens, cost, latency, feature), feature flags per department, a mock provider for tests and for when no key is configured. Features, each with a preview-then-accept UI and its own prompt file and a promptfoo eval set: quick-add parsing in four locales (wire into the work module's quick-add as an enhancement behind the flag), break a card into subtasks, plan my sprint (personal module), explain deadline risk, weekly summary per person and per department (drafts for the inbox digest), draft an event (description, checklist, poll options, carpool plan) from one line, summarise a long comment thread, natural-language analytics ("overdue cards of Data bo'limi this month" → filter grammar + chart choice), translate any text among the four locales, "what did I miss" after time away. Guard rails: content is data, tools allow-listed per feature, no feature reads private contact blocks, summaries cite the cards/events they used. Settings page with budget, flags and usage. Paths: packages/ai/**, apps/api/src/modules/ai, packages/db/src/schema/ai.ts, packages/db/migrations/0800_*.sql, apps/web/src/features/ai/** plus small, clearly-marked integration hooks inside other features (a button/menu item per feature).` },
  { key: 'admin', prompt: `MODULE admin (TECH-SPEC §10, §11, §3.7; TASKS.md EPIC-013). Deliver the super admin console: requests queue (approve/reject with reason — reuse or replace the minimal one from accounts-departments), departments list with view-as (read-only, audited, excludes personal workspaces), pause a department, archive/restore; accounts: search, lock/unlock, reset password (temporary + forced change), 2FA reset, delete/anonymise; global analytics with polished visualisations (departments, people, activity, AI spend); audit viewer with hash-chain verification and export; system health (queues, DB, storage, Telegram, AI endpoint latency, backups); registration open/closed toggle; PAUSE SWITCH: maintenance mode with a message in four locales → branded 503 page everywhere except super admin login/console, API 503, workers pause non-critical jobs, Telegram bot replies with the message; Caddy fallback page in infra; state in instance settings + cache for instant effect; WIPE SWITCH: infra/sentinel (a small host service, Node, systemd unit + Windows service script, listens on 127.0.0.1 only, accepts a command signed with HMAC using a key that lives only in the sentinel config and the encrypted admin settings), console flow: typed phrase, password re-entry, 2FA if enabled, 60-second countdown with cancel; the sentinel stops/removes the project's containers, images and volumes, deletes the project directory, backups and logs under the configured project root, and appends one line to /var/log/devon-wipe.log (or %ProgramData% on Windows); also a host CLI devon-wipe --confirm; everything audited before acting. Paths: apps/api/src/modules/admin, packages/db/src/schema/admin.ts, packages/db/migrations/0900_*.sql, apps/web/src/features/admin/**, infra/sentinel/**, infra/Caddyfile (maintenance fallback), message files.` },
]

// Worktrees are created by the operator before the run: <ROOT>/.claude/worktrees/<key> on branch blitz/<key>
// (the harness's own worktree isolation failed silently on this machine, so we do it by hand and tell the agent).
const WT = (key) => `${ROOT}/.claude/worktrees/${key}`
const runWave = async (name, mods) => {
  phase(name)
  const CONT = (args && args.continue) ? `A PREVIOUS BUILDER ALREADY WORKED ON THIS MODULE in this worktree and its work is committed on your branch. Start with: cd "${'${WT}'}" && git log --oneline master..HEAD && git status && git diff --stat master..HEAD, then read MODULE-GUIDE.md and every file the previous builder created. CONTINUE from there: do not rewrite what works, finish what is missing against the task list below, fix what is broken, make the fast gates green, and commit. ` : ''
  const results = await parallel(mods.map(m => () => mk(`module:${m.key}`, name,
    `${CONT.replace('${WT}', WT(m.key))}YOUR WORKING COPY IS A GIT WORKTREE AT ${WT(m.key)} ON BRANCH blitz/${m.key}. Every Bash command must start with: cd "${WT(m.key)}" && … ; use absolute paths under ${WT(m.key)} for Read/Edit/Write; NEVER read or edit files under ${ROOT}/apps, ${ROOT}/packages or ${ROOT}/e2e directly (that is the main checkout other agents merge into). First run: cd "${WT(m.key)}" && pnpm install --prefer-offline. Commit on your branch as you go. Do not merge, rebase or switch branches. Do not start Docker-dependent servers on shared ports if another agent may be using them — use a random free port for any dev server you start.\n\n${m.prompt}`).then(r => ({ key: m.key, r: r ? { ...r, branch: `blitz/${m.key}` } : null }))))
  const out = results.filter(Boolean)
  for (const { key, r } of out) log(`${name} ${key}: ${r ? r.status : 'died'} — ${r ? r.summary.slice(0, 160) : ''}`)
  return out
}
const merge = async (name, built) => {
  phase(name)
  const branches = built.map(x => `${x.key} → blitz/${x.key} (worktree ${WT(x.key)})`)
  return mk(`merge:${name}`, name, `TASK: integrate the module branches into master in the main checkout ${ROOT}. Branches (module → branch): ${branches.join('; ') || '(none reported: run "git branch --list" and "git worktree list" to find the module branches created in this run)'}. First, in each worktree, commit any uncommitted work the module agent left behind (cd into it, git add -A, git commit -m "<module>: wip"). Then in the main checkout, for each branch in the order given: git merge --no-ff <branch>; resolve conflicts faithfully (both sides are wanted: keep every module's routes, tables, seeds and messages; regenerate merged message catalogues with the i18n build), run "node agentic/scripts/gate.mjs --profile fast" and fix root causes until green, then commit "merge: <module>". After all merges: pnpm install, fast gates green, "pnpm --filter @devon/db migrate:verify" if Docker is available, commit, then remove the worktrees (git worktree remove --force <path>) but keep the branches. Return status and a summary of conflicts resolved. Report branch "master".`)
}
const integrate = async (name, expect) => {
  phase(name)
  return mk(`integrate:${name}`, name, `TASK: make the whole product run. In ${ROOT} on master: start Docker Desktop if needed (start "" "C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe" and wait until "docker ps" works), run "pnpm start --demo" and keep it running in the background (Bash run_in_background), open http://localhost:5173 (or the printed URL) in the in-app browser (mcp__Claude_Browser__navigate), log in with each demo account, and click through EVERY feature listed here: ${expect}. For every runtime error, blank screen, broken navigation, missing translation, failing API call or ugly layout you see: fix the code (root cause), re-run, re-check. Also run the fast gates and "pnpm --filter @devon/web test:e2e" if it exists and fix failures. Take screenshots of each main screen at 1440 and 390 in light and dark into agentic/ledger/blitz/<name>/ (use the browser screenshot tool; save via the JS tool or describe if saving is impossible). Commit fixes as you go ("integrate: <what>"). Return status, the list of routes verified, and remaining known issues in notes. Report branch "master".`)
}

const wave1Modules = ['registration → login → create department → super admin approval → invite link + password → join by link and by form → switcher → settings', 'bo\'limlar nesting + self-assign + org chart (with and without heads)', 'People board with columns per member grouped by bo\'lim, card create/edit/drag/comment/checklist/archive/restore, table/timeline/calendar/mine views, filter grammar URLs, quick-add, group projects with objective and subjective tasks', 'events create/RSVP/waitlist/cancel/comments/carpool/polls/items/photos/feedback/calendar/ICS', 'personal sprints, nested tasks, notes, canvas, Pomodoro widget', 'inbox, preferences, quiet hours, digests, Telegram linking screen and bot commands (mock transport if no token)']
let built1 = []
if (WAVE === 'all' || WAVE === 1 || WAVE === '1') {
  built1 = await runWave('Wave 1', wave1)
  const m1 = await merge('Merge 1', built1)
  log(`merge 1: ${m1 ? m1.status : 'died'} — ${m1 ? m1.summary.slice(0, 200) : ''}`)
  const i1 = await integrate('Integrate 1', wave1Modules.join('; '))
  log(`integrate 1: ${i1 ? i1.status : 'died'} — ${i1 ? i1.summary.slice(0, 200) : ''}`)
}
if (args && args.integrateFirst) {
  const i1 = await integrate('Integrate 1', `${wave1Modules.join('; ')}. NOTE: a previous integration agent already started this pass (its fixes are committed on master, see git log --oneline -15); continue from where it stopped — check what already boots and works before changing anything.`)
  log(`integrate 1 (resumed): ${i1 ? i1.status : 'died'} — ${i1 ? i1.summary.slice(0, 200) : ''}`)
}
let built2 = []
if (WAVE === 'all' || WAVE === 2 || WAVE === '2') {
  built2 = await runWave('Wave 2', wave2)
  const m2 = await merge('Merge 2', built2)
  log(`merge 2: ${m2 ? m2.status : 'died'} — ${m2 ? m2.summary.slice(0, 200) : ''}`)
  const i2 = await integrate('Integrate 2', wave1Modules.concat(['analytics page with filters and pinned charts, Home per role, pages editor with versions, onboarding template on join', 'AI previews: quick-add parse, subtasks, sprint plan, weekly summary, event draft, thread summary, NL analytics, translate (mock provider if no key)', 'super admin console: requests, departments view-as, accounts, audit chain verify, health, pause switch shows the four-locale message and API returns 503, wipe switch flow up to the countdown (do not execute the wipe)']).join('; '))
  log(`integrate 2: ${i2 ? i2.status : 'died'} — ${i2 ? i2.summary.slice(0, 200) : ''}`)
}
return { skeleton: skeleton && skeleton.status, wave1: built1.map(x => ({ key: x.key, status: x.r && x.r.status, branch: x.r && x.r.branch })), wave2: built2.map(x => ({ key: x.key, status: x.r && x.r.status, branch: x.r && x.r.branch })) }
