export const meta = {
  name: 'hardening-blitz',
  description: 'EPIC-014: execute agentic/HARDENING.md H1–H30 against the finished product — baseline measurements, six parallel hardening packages in worktrees, merge, adversarial review sweep, load and web-vitals measurement with the first bottleneck fixed, the six-flow final audit, PRODUCTION-READINESS.md, release gates and the v1.0.0 tag.',
  whenToUse: 'Run once the product and UI are complete. args: {ts, stage: "baseline"|"build"|"sweep"|"measure"|"audit"|"release"|"all", skipBaseline, packages: [keys], continue}.',
  phases: [
    { title: 'Baseline', detail: 'bundle, payloads, query counts, web vitals, p95 at 1/10/100 VUs — before numbers' },
    { title: 'Worktrees', detail: 'one worktree per package on hd/<key>, .env copied so the demo boots' },
    { title: 'Wave', detail: 'security, api-data, resilience-observability, web-perf-a11y, ops-tooling, tests — in parallel' },
    { title: 'Merge', detail: 'merge hd/* branches, integration gates' },
    { title: 'Sweep', detail: 'review-sweep: six lenses, refuters, confirmed findings fixed' },
    { title: 'Measure', detail: 'k6 1/10/100/1000 VUs, 30-min soak, Lighthouse CI on six routes; first bottleneck fixed' },
    { title: 'Audit', detail: 'six flows traced hop by hop; PRODUCTION-READINESS.md sections 1–10' },
    { title: 'Release', detail: 'release gate profile, four-locale changelog, version bump, v1.0.0 tag, backlog updated' },
  ],
}

const TS = (args && args.ts) || 'unstamped'
const STAGE = (args && args.stage) || 'all'
const ROOT = 'C:/Users/rpwal/Documents/Work/eGov/WorkPortal'
const LEDGER = `agentic/ledger/hardening/${TS.replace(/[:+]/g, '-')}`
const WT = (key) => `${ROOT}/.claude/worktrees/hd-${key}`
const run = (s) => STAGE === 'all' || STAGE === s

const CTX = `You are hardening Devon (WorkPortal) for production: a self-hosted department work-tracking platform for a ministry department in Uzbekistan. Stack: pnpm monorepo, apps/api (Fastify 5, Drizzle, Postgres 17 with RLS, pg-boss, Valkey, MinIO, ClamAV, Centrifugo), apps/web (Vite 8, React 19, Tailwind v4, TanStack Query, motion), packages/{db,contracts,ui,i18n,ai,config}, e2e/ (Playwright), infra/ (docker-compose, Caddyfile, sentinel, backup, maintenance). Binding documents: agentic/HARDENING.md (the checklist you execute — cite item ids like H1.4 in every commit message and in your evidence file), agentic/INVARIANTS.md (never breach), docs/03-plan/TECH-SPEC.md (§6 backend, §11 pause/wipe, §12 gates, §13 deployment and operations, §16 standards), MODULE-GUIDE.md (conventions, demo logins), agentic/gates.json (gate profiles: fast, item, integration, release). Docker Desktop is running (devon-postgres, devon-valkey, devon-minio); pnpm start --demo boots the app with a seeded demo (read scripts/start.mjs for the port env vars so you can boot on free ports). Tools: semgrep is on PATH; k6 runs as docker run --rm -i --network host grafana/k6 (or the image's documented invocation on Windows: publish ports and target host.docker.internal); trivy as docker run --rm aquasec/trivy; Lighthouse CI via npx @lhci/cli@<exact version> with CHROME_PATH pointing at Playwright's Chromium (npx playwright install chromium if missing).
TOOLING REQUIREMENTS: first run ToolSearch with query "select:LSP" and use the LSP tool for every TypeScript symbol lookup and refactor instead of grep; use the chrome-devtools MCP (performance traces, lighthouse_audit, network and CPU emulation, heap snapshots) and the playwright MCP for all browser measurement; measure, never describe.
RULES: "Implement, don't describe" — where an item is unmet, fix it; only items needing infrastructure agents cannot touch go into the evidence file's "requires external configuration" list with exact instructions. Never weaken a test, gate, policy or invariant to pass; never edit an applied migration (add a new one); never commit secrets; pin exact versions for anything you add. Keep every existing behaviour working: the fast gates (node agentic/scripts/gate.mjs --profile fast) must be green before every commit, and run pnpm --filter @devon/db migrate:verify whenever you touch packages/db. Commit early and often with messages "<H-ids>: <what changed>". Write your evidence file as instructed with, per item: status (done | already-met | external), the evidence (command output, file path, measurement) and the commit. Return a JSON result matching the schema.`

const DONE = { type: 'object', properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, branch: { type: 'string' }, commits: { type: 'number' }, summary: { type: 'string' }, items_done: { type: 'array', items: { type: 'string' } }, items_external: { type: 'array', items: { type: 'string' } }, gates_green: { type: 'boolean' }, notes: { type: 'string' } }, required: ['status', 'summary'] }
const mk = (label, phase, prompt, extra) => agent(`${CTX}\n\n${prompt}`, { label, phase, agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: DONE, ...(extra || {}) })

// ---------- Baseline ----------
let baseline = null
if (run('baseline') && !(args && args.skipBaseline)) {
  phase('Baseline')
  baseline = await mk('baseline', 'Baseline', `TASK in ${ROOT} on master (measure, do not change product code; you may add measurement scripts under tools/perf/ and commit them): produce the BEFORE numbers HARDENING.md asks for, written to ${ROOT}/${LEDGER}/baseline.md with the exact commands so the same measurement can be repeated after. Boot pnpm start --demo. Measure: (1) production bundle: pnpm --filter @devon/web build, per-chunk gzip sizes, node agentic/scripts/check-bundle.mjs; (2) the six main routes (/, /work, /work/table, /events, /inbox, /analytics) as demo.boshliq: number of requests, bytes transferred, number of API calls, duplicate requests and waterfalls (Playwright with request logging), and the API's SQL query count per route (enable statement logging in Postgres or count via pg_stat_statements — add it to the compose file if missing); (3) Core Web Vitals LCP/INP/CLS on those routes at simulated 4G via Lighthouse CI (npx @lhci/cli, exact version, Playwright's Chromium) — record the Lighthouse JSON paths; (4) API latency p50/p95/p99 at 1, 10 and 100 virtual users for board load (GET the board), card move (PATCH), RSVP (POST) and analytics summary, with k6 scripts you write under tools/perf/k6/ (docker run grafana/k6); note whether 1000 VUs is feasible on this machine and try it for 60 s; (5) memory of the API process during a 10-minute soak at 10 VUs (RSS sampled every 30 s); (6) the current state of the gates: node agentic/scripts/gate.mjs --profile release --json and Read agentic/ledger/last-gate.json, listing which gates are red or skipped and why. Commit tools/perf/ and the baseline file. Report branch "master".`)
  log(`baseline: ${baseline ? baseline.status : 'died'} — ${baseline ? baseline.summary.slice(0, 200) : ''}`)
}

// ---------- Packages ----------
const packages = [
  { key: 'security', model: 'opus', paths: 'apps/api (plugins, config, error handling, uploads, telegram webhook, rate limits, redaction), packages/contracts (schemas, permissions), packages/db (new migrations only: DB role grants, constraints), infra/Caddyfile (headers), apps/web only for CSP nonce plumbing and the sanitiser', prompt: `PACKAGE security — H1.1–H1.16, H16, H17 (server side), H1.14 Telegram. Audit and fix every item: secrets scan and log redaction (passwords, tokens, codes, contact blocks); can() + RLS on every endpoint with an object-level access test that swaps ids across departments; Zod allow-lists on every write (no mass assignment; ownership, roles, ids, computed values never from the client); argon2id, session cookie flags, rotation on login, expiry, CSRF double-submit, logout everywhere; XSS: Tiptap schema allow-list, DOMPurify on any HTML, CSP with nonces via Caddy/Fastify, no dangerouslySetInnerHTML outside the sanitiser; validation of type/size/format/range/enum/id/URL with SSRF-safe unfurling (block private ranges, redirects re-checked), filename and sniffed MIME; parameterised queries only (grep for string SQL from input); uploads: allow-lists, random keys, ClamAV path, private signed URLs; rate limits with progressive lockout and uniform responses/timing on login, register, join, reset, 2FA, AI, uploads; helmet-equivalent headers (HSTS, CSP, frame-ancestors none, referrer, permissions policy) and CORS allow-list; responses never leak hashes/tokens/internal ids/others' private fields; RFC 9457 errors with request id and no stack/SQL/paths in production; Telegram webhook secret token, Mini App initData HMAC, webhook signatures with a replay window; all codes/keys from CSPRNG, hashed at rest, expiring, single-use; privilege-escalation negative tests member→head→super admin; least-privilege DB role (app role INSERT/SELECT only on audit — verify with migrate:verify). Production config: env validated with Zod at boot (fail fast), secure cookies, trustProxy for Caddy, log level info, no console.log, demo seed and dev endpoints only behind --demo. Write ${LEDGER}/security.md.` },
  { key: 'api-data', paths: 'apps/api (repos, services, routes: pagination, ETag, compression, timeouts, streaming, idempotency), packages/db (new migrations for indexes and constraints; EXPLAIN evidence), packages/contracts (list/summary shapes, cursor types), apps/web only where a list endpoint\'s shape change requires the client to follow', prompt: `PACKAGE api-data — H2, H3, H7, H9, H10, H14, H27. Compression (brotli/gzip) on compressible responses; list endpoints return summary shapes with cursor pagination and server-side filter/sort/search (no full objects, no offset pagination on hot lists); ETag/If-None-Match on GETs and Cache-Control private,no-store on authenticated JSON; immutable fingerprinted assets; timeouts on every outbound call, retries only for idempotent transient failures with backoff+jitter+cap; streaming for CSV exports and large files; measure payload before/after on the six main routes. Database: no N+1 (relational queries or batched loads; add a Semgrep rule for query-in-loop under tools/semgrep/ and fix violations); bulk inserts for seeds/digests/fan-out; pool sizing per process and PgBouncer-safe set_config(..., true); indexes justified by access patterns with EXPLAIN ANALYZE evidence before/after in your evidence file (department_id+assignee+status+due, department_id+project_id, order keys, FTS GIN, trigram GIN on names, notifications user_id+read_at) and redundant indexes dropped; no select *; transactions around multi-row writes; row versions for optimistic concurrency; unique constraints for idempotency (idempotency_keys, RSVP (event_id,user_id), poll (poll_id,option_id,voter_hash)); expand/contract migrations tested twice on Testcontainers. Handlers: no sync fs or CPU-heavy work, parallel independent I/O, expensive work to pg-boss; clients/pools reused; body/JSON-depth/upload/AI-input limits. Cache map written (browser/Caddy/Valkey/query/computation: key, TTL, invalidation, user isolation) with stampede protection on analytics aggregates. Concurrency: RSVP/seat/poll races tested with parallel requests; job idempotency; webhook replay protection. Integrity: FKs and cascade rules reviewed, UTC + tz, UZS as integer, NFC-normalised Uzbek modifier letters, state transitions enforced and tested. Cost: AI calls cached by prompt hash where deterministic, digests batched, logs bounded. Write ${LEDGER}/api-data.md.` },
  { key: 'resilience-observability', paths: 'apps/api (plugins for logging/metrics/health/shutdown, jobs, integrations adapters for AI/Telegram/ClamAV/MinIO/Centrifugo), apps/web/src/features/admin only for the health page data contract, infra/docker-compose.yml only for healthchecks', prompt: `PACKAGE resilience-observability — H8, H11, H12, H13, H15. Timeouts and circuit breakers for AI, Telegram, ClamAV, MinIO, Centrifugo with graceful degradation (AI off → features hide and say so; Telegram down → inbox still works and queues; ClamAV down → uploads queue as pending-scan; MinIO down → clear error, no crash); no third-party scripts, fonts/illustrations self-hosted (verify); single points of failure listed with mitigation. Bounded queues/caches/maps; streaming for files; timers cleared; sockets closed. Stateless API (sessions in Valkey/DB, verified by running two API instances against one DB), worker horizontally scalable, pool and connection limits computed and documented. Verify behaviour with each dependency stopped (docker stop) and slow (tc/proxy or a fault-injection flag): health/readiness endpoints reflect it, graceful shutdown drains in-flight requests and jobs, dead-letter queue for failed jobs with an admin view, safe restart. Observability: structured JSON logs with request/user/department ids, latency histograms per route, DB timing, queue metrics, AI latency/cost, error rates, a slow-request log, a /metrics endpoint (Prometheus format) behind auth or loopback, and the admin health page reading real numbers. Write ${LEDGER}/resilience-observability.md.` },
  { key: 'web-perf-a11y', paths: 'apps/web, packages/ui, packages/i18n messages, e2e (a11y-tagged specs and vitals scripts), infra/Caddyfile only for asset cache headers', prompt: `PACKAGE web-perf-a11y — H2.4, H4, H5, H6, H21, H22, H23, H24, plus the three open UI items from agentic/ledger/ui-blitz/*/round3/report.md (people hover card contact actions, the two others it names, and the mobile table). Profile before optimising (React Profiler traces saved to the evidence folder); React Compiler on; virtualise boards, tables, archives, activity timelines; route-level code splitting with Excalidraw, FullCalendar, charts and Tiptap lazy; size-limit with the shell ≤ 200 kB gz and no duplicate packages (pnpm why); no layout thrash, compositor-only animations, content-visibility on long lists; cleanup of listeners/timers/sockets/observers with a heap snapshot before/after navigation in the evidence. Optimistic updates for card moves, status, RSVP, checklist, comments, personal tasks with rollback toasts; skeletons match layout; stale data kept during revalidation; prefetch on hover/focus; idempotency keys and per-control pending state against double submit; kept-alive panels and View Transitions. Query dedupe: no duplicate requests on mount, loaders prefetch in parallel (verify with the request log from the baseline). Assets: WebP/AVIF with responsive sizes and lazy loading, avatars 64/128/512; fonts subset to Latin Extended + Cyrillic + modifier letters with font-display swap and only critical faces preloaded; fingerprinted 1-year immutable assets; source maps not public; unused CSS/assets removed with bytes saved. Accessibility: semantic HTML validated, keyboard and focus complete on every primary flow, labels, contrast, reduced motion, alt text, ARIA patterns for custom controls; tag e2e specs with @a11y so pnpm --filter @devon/web test:a11y runs axe on every route with 0 serious/critical. Web basics: titles/meta on login/join/maintenance, robots.txt disallowing the app, app routes noindex, correct status codes. Core Web Vitals: LCP < 2.5 s, INP < 200 ms, CLS < 0.1 on the six main routes at 4G via Lighthouse CI, with a committed lighthouserc and perf:check script wired to the perf gate. Write ${LEDGER}/web-perf-a11y.md with before/after numbers.` },
  { key: 'ops-tooling', paths: 'infra/, .github/workflows, root package.json scripts, tools/ (semgrep rules, madge/knip configs, perf and security scan wrappers), docs/ops/, Dockerfiles, scripts/', prompt: `PACKAGE ops-tooling — H17 (build), H18, H19, H20, H28, H29, H1.12, and the gate wiring for security:scan and perf:check. Production builds: multi-stage Dockerfiles for api, web (static behind Caddy) and worker with pinned base-image digests, non-root users, healthchecks; a production docker-compose (separate from dev) with Caddy forcing HTTPS, resource limits, restart policies, log rotation; env validated; secure defaults. Deployment: reproducible builds, migrations run before rollout with backward compatibility, readiness gating, documented rollback, graceful shutdown, jobs preserved — write docs/ops/DEPLOY.md and docs/ops/RUNBOOK.md (restart, rotate secrets, restore, pause, wipe, upgrade). Backups: pgBackRest (or pg_dump-based if pgBackRest cannot run here — say which and why) plus a MinIO mirror, retention 30 days + monthly for a year, automated weekly restore verification script, quarterly drill script, encryption, secrets excluded — run one full backup and restore into a scratch database and record the result. Dependencies: remove unused (knip), dedupe, justify heavy libs, npm audit high = 0, abandoned packages replaced, prod vs dev deps separated; Renovate config committed. Architecture: madge circular-dependency check green, knip dead-code check green (or a documented allowlist), no hardcoded URLs (grep). Semgrep rules under tools/semgrep/ for await-in-loop over independent items, query-in-loop, sync fs in handlers, polling; wire pnpm -w security:scan (semgrep + trivy fs and image scans) and pnpm -w perf:check (lhci + k6 smoke) into root package.json so the integration and release gate profiles run them; CI (.github/workflows/ci.yml) runs the release profile on tags and the integration profile on pushes, with Testcontainers Postgres. Write ${LEDGER}/ops-tooling.md.` },
  { key: 'tests', paths: 'apps/api/test, apps/web/test, packages/*/test, e2e/ (specs and fixtures), packages/db/src/seed only if a fixture is needed', prompt: `PACKAGE tests — H25, H1.2 and H1.16 (as tests), H10.1 (as tests), H30 flows (as e2e). Add the tests that prove the hardening, without touching product code (if you find a product bug, write the failing test, describe it in your evidence file for the merge agent, and continue): cross-department object-level access tests that swap ids for every entity type (cards, projects, events, polls, pages, units, memberships, notifications, personal tasks, AI settings, admin routes); privilege escalation negative tests member→head→super admin and admin routes as head; mass-assignment tests (role, department_id, user_id, computed fields in bodies are ignored or rejected); validation matrix tests (type/size/range/enum/url/filename/mime); rate-limit and lockout tests with uniform responses; idempotency and race tests (parallel RSVP on the last seat, parallel poll votes, parallel card moves, duplicate idempotency keys) against real Postgres (Testcontainers); state-transition tests; audit-immutability tests (UPDATE/DELETE on audit.events fail for the app role); session tests (rotation, expiry, logout everywhere, CSRF); e2e for the six flows in H30.1 (register→department→invite→join; board move; group project with objective and subjective tasks; sprint + Pomodoro; event with carpool + poll; admin pause) tagged @flow, and @smoke kept fast. Remove meaningless tests you find (tests that cannot fail). All suites must run under the existing scripts (test:unit, test:e2e, test:a11y) and be green. Write ${LEDGER}/tests.md with the coverage map (item id → test file).` },
]
const selected = (args && Array.isArray(args.packages) && args.packages.length) ? packages.filter(p => args.packages.includes(p.key)) : packages
let built = []
if (run('build')) {
  phase('Worktrees')
  const setup = await agent(`In ${ROOT}: for each key in [${selected.map(p => p.key).join(', ')}]: if "${ROOT}/.claude/worktrees/hd-<key>" exists leave it; else if branch hd/<key> exists run git worktree add "${ROOT}/.claude/worktrees/hd-<key>" hd/<key>; else run git worktree add "${ROOT}/.claude/worktrees/hd-<key>" -b hd/<key> master. Then copy the local env file into each new worktree so the demo can boot there: cp "${ROOT}/.env" "${ROOT}/.claude/worktrees/hd-<key>/.env" (it is gitignored; do not print its contents). Return {"status":"DONE","summary":"<git worktree list output and which copies succeeded>"}.`, { label: 'worktrees', phase: 'Worktrees', agentType: 'general-purpose', model: 'sonnet', effort: 'low', schema: DONE })
  log(`worktrees: ${setup ? setup.summary.slice(0, 300) : 'died'}`)

  phase('Wave')
  const CONT = (args && args.continue) ? `A PREVIOUS AGENT ALREADY WORKED ON THIS PACKAGE in this worktree; its work is committed on your branch and its evidence file may exist. Start with git log --oneline master..HEAD && git status && git diff --stat master..HEAD and the evidence file; CONTINUE — do not redo what is done. ` : ''
  const results = await parallel(selected.map(p => () => mk(`hd:${p.key}`, 'Wave', `${CONT}YOUR WORKING COPY IS A GIT WORKTREE AT ${WT(p.key)} ON BRANCH hd/${p.key}. Every Bash command must start with: cd "${WT(p.key)}" && … ; use absolute paths under ${WT(p.key)} for Read/Edit/Write; NEVER read or edit files under ${ROOT}/apps, ${ROOT}/packages, ${ROOT}/infra or ${ROOT}/e2e directly. First: cd "${WT(p.key)}" && pnpm install --prefer-offline. You may edit ONLY: ${p.paths}. Boot your own copy on free ports when you need the running app (read scripts/start.mjs for the env vars; the shared Postgres in Docker is fine; use a separate database name if your migrations could disturb others: create it and set DATABASE_URL for your processes). Read ${ROOT}/${LEDGER}/baseline.md if it exists for the BEFORE numbers. Commit on your branch as you go; do not merge, rebase or switch branches.\n\n${p.prompt}\n\nFinish with node agentic/scripts/gate.mjs --profile fast green in your worktree, the evidence file written, and the result listing items_done and items_external.`, { model: p.model || 'sonnet' }).then(r => ({ key: p.key, r: r ? { ...r, branch: `hd/${p.key}` } : null }))))
  built = results.filter(Boolean)
  for (const { key, r } of built) log(`wave ${key}: ${r ? r.status : 'died'} — ${r ? r.summary.slice(0, 160) : ''}`)

  phase('Merge')
  const m = await mk('merge', 'Merge', `TASK: integrate the hardening branches into master in ${ROOT}: ${built.map(x => `${x.key} → hd/${x.key} (worktree ${WT(x.key)})`).join('; ') || '(run git branch --list "hd/*" and git worktree list)'}. In each worktree commit any uncommitted work first. Merge in this order (least overlap first): tests, ops-tooling, web-perf-a11y, resilience-observability, api-data, security — with git merge --no-ff; resolve conflicts keeping both intents (plugin registration order: security headers and rate limits before routes; package.json: union of scripts and deps; migrations: renumber to keep filename order unique and re-run migrate:verify). After each merge: pnpm install, node agentic/scripts/gate.mjs --profile fast, and fix what broke before the next. The tests package may have left failing tests that document product bugs it could not fix — read ${LEDGER}/tests.md and fix those bugs at the root cause now (never delete or weaken the tests). Then run node agentic/scripts/gate.mjs --profile integration (typecheck, lint, unit, i18n, secrets, build, migrate, e2e, a11y, bundle, security) and make it green with nothing skipped: security needs semgrep on PATH and trivy via Docker (the ops-tooling package wired pnpm -w security:scan). Remove the hd-* worktrees, keep the branches. Merge the six evidence files into ${LEDGER}/evidence.md (one table: item id → status → evidence → commit). Commit. Report branch "master".`)
  log(`merge: ${m ? m.status : 'died'} — ${m ? m.summary.slice(0, 200) : ''}`)
}

// ---------- Sweep ----------
if (run('sweep')) {
  phase('Sweep')
  const sw = await workflow({ scriptPath: `${ROOT}/.claude/workflows/review-sweep.js` }, { scope: 'apps/ packages/ infra/', maxRounds: 2, fix: true })
  log(`sweep: ${JSON.stringify(sw).slice(0, 300)}`)
}

// ---------- Measure ----------
if (run('measure')) {
  phase('Measure')
  const me = await mk('measure', 'Measure', `TASK in ${ROOT} on master: the AFTER measurements and the first bottleneck (H2.9, H4.6, H11.1, H12.1, H24.1, H26.1). Repeat every measurement in ${LEDGER}/baseline.md with the same commands (bundle, six-route requests/bytes/API calls/queries, Lighthouse CI vitals at 4G, k6 p50/p95/p99 at 1/10/100 and 1000 VUs for board load, card move, RSVP burst, analytics, AI with the mock provider), then run the 30-minute k6 soak at 10 VUs sampling API RSS every 30 s — memory must be flat; investigate any growth with a heap snapshot. Find the first bottleneck (highest p95 or the first error under load), fix it at the root cause, re-measure, and repeat once more if a second is obvious. Write ${LEDGER}/measurements.md with before/after tables and the k6/Lighthouse artefact paths; commit tools/perf changes and the fixes with H-ids. Fast gates green. Report branch "master".`)
  log(`measure: ${me ? me.status : 'died'} — ${me ? me.summary.slice(0, 200) : ''}`)
}

// ---------- Audit ----------
if (run('audit')) {
  phase('Audit')
  const au = await mk('audit', 'Audit', `TASK in ${ROOT} on master — H30.1 and the report. Trace the six user flows end to end against the running demo (pnpm start --demo; demo logins in MODULE-GUIDE.md): register→create department→super admin approves→invite→join; board card move; group project with objective and subjective tasks; sprint + Pomodoro session; event with carpool + poll; admin pause and resume. For every hop (each request) record time, bytes, SQL query count and CPU where measurable, before (from ${LEDGER}/baseline.md where the route was covered, else mark n/a) and after; fix anything that is clearly wrong on the way (an extra query, a duplicate request) with an H-id commit. Then write docs/03-plan/PRODUCTION-READINESS.md with sections 1–10: 1 scope and method, 2 security (H1, H16, H17 evidence), 3 API and data (H2, H3, H7, H9, H10, H14, H27), 4 frontend and web vitals (H4, H5, H6, H21–H24), 5 resilience and observability (H8, H11–H13, H15), 6 tests and load (H25, H26, the k6 tables), 7 operations (H17–H20, H28, H29), 8 the six flow traces, 9 open items with owners, 10 required external configuration with exact instructions (TLS certificates and domain, Telegram bot token and webhook, AI_API_KEY, SMTP if any, backup target credentials, server sizing). Every claim cites ${LEDGER}/evidence.md, ${LEDGER}/measurements.md or a command you ran; no item may be described as done without evidence. Commit. Report branch "master".`, { model: 'opus' })
  log(`audit: ${au ? au.status : 'died'} — ${au ? au.summary.slice(0, 200) : ''}`)
}

// ---------- Release ----------
if (run('release')) {
  phase('Release')
  const rel = await mk('release', 'Release', `TASK in ${ROOT} on master — release 1.0.0. Run node agentic/scripts/gate.mjs --profile release --json (typecheck, lint, unit, i18n, secrets, build, migrate, e2e, a11y, bundle, security, perf, deps) and make it green with NOTHING skipped: if perf or security is skipped, wire or install what is missing (lhci via npx with Playwright's Chromium, k6 via Docker, semgrep on PATH, trivy via Docker) rather than accepting the skip; fix real failures at the root cause. Then: bump every workspace package to 1.0.0; write CHANGELOG.md with a 1.0.0 entry in all four locales (uz-Latn, uz-Cyrl, ru, en) in plain language for a department head; refresh the demo seed if anything changed; update docs/03-plan/backlog.json via node agentic/scripts/backlog.mjs set-status for EPIC-001 through EPIC-014 → done with evidence pointers (the blitz merges, the ui-blitz reports, ${LEDGER}/evidence.md, docs/03-plan/PRODUCTION-READINESS.md); append the ledger entry (node agentic/scripts/ledger.mjs); commit "release: 1.0.0"; create the annotated git tag v1.0.0 locally (do not push anything). Report branch "master" with the final gate JSON summary in notes.`)
  log(`release: ${rel ? rel.status : 'died'} — ${rel ? rel.summary.slice(0, 200) : ''}`)
}

return { stage: STAGE, baseline: baseline && baseline.status, wave: built.map(x => ({ key: x.key, status: x.r && x.r.status })) }
