export const meta = {
  name: 'recon',
  description: 'Reconnaissance before v1.1: map the codebase as it is now, audit permissions per role, audit the AI features, research ClickUp, and walk the running product as member and head to list everything gray, broken or unpolished. Read-only except the report files.',
  whenToUse: 'Before writing the v1.1 spec. args: {ts}.',
  phases: [{ title: 'Recon', detail: 'five parallel Opus investigators → docs/03-plan/v1.1/*.md' }],
}
const ROOT = 'C:/Users/rpwal/Documents/Work/eGov/WorkPortal'
const OUT = 'docs/03-plan/v1.1'
const DONE = { type: 'object', properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, summary: { type: 'string' }, file: { type: 'string' }, notes: { type: 'string' } }, required: ['status', 'summary'] }
const CTX = `Devon (WorkPortal) is a self-hosted department work-tracking platform for a ministry department in Uzbekistan (uz-Latn default, uz-Cyrl, ru, en). Roles are exactly super_admin, head (boshqarma boshlig'i — the department head), member (xodim). Binding documents: CLAUDE.md (read first — it lists the new tooling: TypeScript LSP tool for symbol lookups instead of grep, chrome-devtools and playwright MCPs for browser work), docs/03-plan/TECH-SPEC.md, docs/03-plan/FEATURE-PLAN.md, DESIGN.md, MODULE-GUIDE.md (demo logins: demo.boshliq = head, demo.xodim = member, admin.super = super admin; password in packages/db/src/seed/fixtures.ts), agentic/INVARIANTS.md. Another agent is merging hardening branches into master at the same time: READ ONLY — do not edit product code, do not commit; write only your report file under ${ROOT}/${OUT}/. Be concrete: file paths, route paths, component names, screenshots where relevant. Return the report path in "file".`
const mk = (key, prompt, extra) => agent(`${CTX}\n\n${prompt}`, { label: `recon:${key}`, phase: 'Recon', agentType: 'general-purpose', model: 'opus', effort: 'high', schema: DONE, ...(extra || {}) })

phase('Recon')
const jobs = [
  mk('codebase-map', `Write ${OUT}/STATE.md — the map of the codebase as it is today. Sections: (1) repo layout and package graph (use the LSP tool and package.json files); (2) apps/api: every module with its routes (method, path, the can() action it checks, which role passes), jobs, domain events emitted/consumed; (3) apps/web: every feature manifest with routes, sidebar entries, palette entries, the screens per route, which role sees them; (4) packages: db schema tables per module (with department_id / user_id ownership and RLS policy names), contracts (permissions.ts actions and the matrix), ui primitives and motion pieces, i18n layout, ai package structure; (5) the agentic system and tooling as of now (workflows, agents, hooks, gates, plugins, MCPs, skills, evidence ledgers) and how a build is launched; (6) what is on unmerged branches (git branch --list "hd/*" "claude/*" with git log master..<branch> — summarise per branch); (7) known gaps and TODOs found in code and in agentic/ledger reports; (8) how to boot and test (commands, ports, demo logins). 600–1200 lines, every claim with a path.`),
  mk('permissions-audit', `Write ${OUT}/PERMISSIONS-AUDIT.md. The CTO tested the product and found features meant for the head (boshqarma boshlig'i) visible to normal members (xodim), and wants every feature re-decided for member / head / super admin. Do: (1) extract the actual matrix from packages/contracts/src/permissions.ts (every action, who passes) and from every apps/api route (which can() action each route uses; routes with no can() call; routes where the check is weaker than the UI implies) — use the LSP tool findReferences on can() to enumerate; (2) enumerate every UI surface in apps/web (sidebar entries, page headers, buttons, menus, tabs, settings sections, admin-only screens) and note whether it is hidden for members, and whether the server enforces it; (3) produce the PROPOSED matrix as a table per feature area (accounts, departments, structure, work/cards, projects, events, personal, inbox/telegram, analytics, pages, ai, admin) with columns member / head / super admin, each cell allow / own-only / deny, with a one-line rationale grounded in how a ministry department works (a member manages their own work and can see the team's board; a head manages people, structure, assignments, settings, analytics for everyone, custom fields, invitations; a super admin manages the instance). Mark every DIFFERENCE between actual and proposed with severity (leak of head-only data to members = SEV1). (4) list the exact code changes needed (files, functions) to enforce the proposed matrix on the server first and hide in the client second.`),
  mk('ai-audit', `Write ${OUT}/AI-AUDIT.md. The CTO says the AI features feel random, "gray", and seem to mostly translate to Uzbek. For EVERY AI feature in packages/ai (prompts, schemas, feature registry) and its UI in apps/web (features/ai and every host screen that calls useRunAiFeatureMutation / SparkleButton / AiPreviewPanel): (1) what it does today — the exact system/user prompt text, the output schema, where the output goes, what the user sees before/after, and whether it works with the mock provider and with a real key (packages/ai config: AI_API_KEY, AI_BASE_URL https://api-llm.gpu.uz/v1, model glm-5.2, reasoning-first so max_tokens ≥ 1024, tool calling; docs/03-plan/integrations/glm-api-instruction.md); (2) what a department member or head would actually want from AI at that spot (be specific and practical: e.g. quick-add should turn "Nodira: EGDI paketi juma" into assignee, title, due date, labels with confidence; sprint plan should look at open cards, capacity and deadlines and propose an ordered plan with reasons; weekly summary should be a head's Monday briefing with risks and who is overloaded; thread summary should extract decisions and open questions; event draft should produce a complete event from a one-line intent; NL analytics should map a question to the filter grammar and answer with numbers; translate should preserve terminology from packages/i18n/TERMS.md); (3) a unique, complete prompt specification per feature: role, inputs (which data is fetched and in which shape), instructions, constraints (language = the user's locale; Uzbek Latin with correct oʻ/gʻ; never invent people or dates; cite card ids), output JSON schema, few-shot examples, evaluation cases for the golden set; (4) UI expectations: where the affordance sits, what the preview shows, accept/edit/discard semantics, empty and error states, cost line; (5) which features to drop or merge and which new ones are worth adding (e.g. "explain this risk badge", "draft a reply", "suggest who to assign", "what changed since Friday"). Also check the gateway: reasoning_content handling, retries, budget, traces, and whether streaming or a fake-streaming skeleton is used.`),
  mk('clickup-research', `Write ${OUT}/CLICKUP-RESEARCH.md. Research ClickUp (WebFetch help.clickup.com, clickup.com/features, the public docs on Custom Fields, Views (List, Board, Table, Calendar, Gantt, Workload, Timeline, Everything, Me mode), Dashboards and cards, Goals/Targets, Time estimates and tracking, Dependencies, Recurring tasks, Templates, Automations, Reminders, Notifications, LineUp, Multitask toolbar, Home/My Work, Custom task statuses and priorities, Tags, Sprints, Docs, Whiteboards, ClickApps). For each feature: what it is, why users love it (Jakob's Law: what people already know), and a verdict for Devon — adopt as is / adapt (how) / skip (why) — given the product (department board with a column per person, group projects, personal workspace, events, inbox+Telegram, analytics, pages, AI, super admin console; no HR, no documents suite, no chat). Then a prioritised adoption list for v1.1 with a concrete UX spec per item (where it lives, default behaviour, what the head configures, what the member sees), emphasising: Custom Fields (on people AND on cards, typed: text, number, date, select, person, url, checkbox, formula-lite), Workload view (capacity per person per week), Table view with saved views and dynamic columns, Dependencies and time estimates, Recurring tasks and templates, Dashboards/widgets for the head, Me mode / My Work / LineUp, multitask toolbar, Goals for the department. Cite URLs.`),
  mk('walkthrough', `Write ${OUT}/WALKTHROUGH-FINDINGS.md by actually using the product like a demanding user, on a copy so the merge in progress does not disturb you: cd ${ROOT} && git worktree add --detach ${ROOT}/.claude/worktrees/recon-app master && cp ${ROOT}/.env ${ROOT}/.claude/worktrees/recon-app/.env && cd ${ROOT}/.claude/worktrees/recon-app && pnpm install --prefer-offline && set API_PORT=3200 WEB_PORT=5200 (read scripts/start.mjs for how ports are passed) && pnpm start --demo (Docker devon-postgres/valkey/minio are up). Use the chrome-devtools MCP (mcp__chrome-devtools__navigate_page, take_snapshot, click, fill, take_screenshot) or the in-app browser. Walk EVERYTHING twice: once as demo.xodim (member) and once as demo.boshliq (head), plus the super admin console as admin.super, at 1440 and 390, in uz-Latn (default) and ru. For every screen and flow record: what a member sees that only a head should (SEV1), what is broken (errors, dead buttons, wrong data), what is gray/empty/unpolished/annoying (empty states without guidance, jargon, unclear copy, too many clicks, missing feedback, layout issues), what is missing that a user obviously expects at that spot, and the AI affordances (do they produce something useful or just translate?). Rank findings by impact with the route, the persona, and a screenshot path (save PNGs under ${OUT}/walkthrough/). End with a "top 30 things to fix first" list and a one-paragraph honest verdict on how far the product is from something a ministry department would enjoy using daily. Stop your own processes at the end and leave the worktree (do not remove it).`, { effort: 'high' }),
]
const res = await parallel(jobs.map(j => () => j))
for (const r of res) log(`${r ? r.status : 'died'} ${r ? r.file : ''} — ${r ? r.summary.slice(0, 160) : ''}`)
return res.map(r => r && { status: r.status, file: r.file })
