export const meta = {
  name: 'research-sweep',
  description: 'Exhaustive research sweep for the ministry internal-ops platform: 18 dimensions, verified, then vision drafts judged and synthesized',
  phases: [
    { title: 'Research', detail: '18 parallel research agents, each writes docs/01-research/<key>.md' },
    { title: 'Verify', detail: 'completeness critic + spot fact-check per dimension, gap-fill pass' },
    { title: 'Matrix', detail: 'competitive feature matrix across all researched products' },
    { title: 'Vision', detail: '3 independent vision drafts from different lenses' },
    { title: 'Judge', detail: '3 judges score the drafts and harvest best ideas' },
    { title: 'Synthesize', detail: 'merged feature-plan draft' },
  ],
}

const ROOT = 'C:/Users/rpwal/Documents/Work/eGov/WorkPortal'
const RESEARCH_DIR = `${ROOT}/docs/01-research`
const SYNTH_DIR = `${ROOT}/docs/02-synthesis`
const AUDIT = `${ROOT}/docs/00-reference/reference-site-audit.md`

const CONTEXT = `
PROJECT CONTEXT (read carefully, this frames everything):
We are building an internal operations platform for a department of the Ministry of Digital Technologies of Uzbekistan (Department of Information & Analytical Activities: director + 4 sub-departments: Strategy & Rankings (EGDI, global indices), Data & BI Analytics, Innovation & Digital Transformation, Economic Development & FinTech; ~23 people today). It must be scalable and shareable to other departments and ministries (multi-tenant), and the explicit ambition is that it "goes viral" across government for its UI/UX, ease of use, and power. The user's core tension: Jira-level power WITHOUT Jira-level learning curve; Notion-level flexibility but opinionated and unique to what a Uzbek government department actually needs. A first-time civil servant must understand it without training. Languages: Uzbek (Latin), Russian, English. Telegram is the dominant messenger in Uzbekistan. Personal data of citizens/employees must be stored in Uzbekistan (data localization law). Likely on-premise or gov-cloud deployment.
The reference prototype (static, read-only) is summarized in ${AUDIT} — read it first (use the Read tool). It has: Overview KPIs, People directory with privacy tiers, Organization chart + sub-department mandates, Projects register with weekly-comment ritual and auto-escalation, Activities (team events with RSVP), and a 3-phase roadmap (reliable records → connected workflows → decision intelligence).
Today's date: 2026-09-04. Prefer 2025–2026 sources; note version numbers and dates.
`

const RESEARCH_RULES = `
HOW TO WORK:
- Use WebSearch extensively (at least 12 distinct searches, vary phrasing; search for 2026/2025 content) and WebFetch to read the most valuable pages in full (at least 8 fetched pages). Do not answer from memory alone; every important claim should carry a source URL.
- Think like a senior product designer + staff engineer who has used these tools daily, not like a summarizer. Extract concrete, specific, actionable details: exact UX patterns, interaction details, keyboard shortcuts, data models, library names with versions, license names, pricing/limits, adoption numbers, known failure modes and complaints.
- Explicitly hunt for CONTRARIAN and NEGATIVE evidence: what users hate, what failed, what bloated, what governments rejected and why.
- End with a section "What this means for us" with 8–15 numbered, opinionated recommendations tied to our context (Uzbek ministry, multi-tenant, zero-training UX), each marked [ADOPT] / [ADAPT] / [AVOID] and a one-line why.
- Also include a section "Open questions" (things you could not verify or that need a decision by the product owner).
- WRITE the full report as Markdown to the exact file path given (use the Write tool; create it fresh). Length: 1,500–4,000 words of dense substance, no filler, no marketing language. Use tables where comparing. Put a "Sources" list at the end with every URL used.
- Your final structured output must summarize the report; the file on disk is the real deliverable.
`

const DIMENSIONS = [
  { key: 'work-management-landscape', title: 'Work-management product landscape',
    brief: `Deep-dive the work/project management category: Linear (the Linear Method, speed, keyboard-first, opinionated cycles/projects/initiatives, triage, its sync engine reputation), Asana, ClickUp (and its bloat critique), Monday.com, Height, Basecamp (calm, opinionated, Hill charts), Fibery, Coda, Shortcut, Wrike, Smartsheet, Airtable. For each: the 3 features users love, the top complaints, how they onboard, pricing model, what they do for portfolio/status reporting. Dedicated section on WHY JIRA IS HATED (with real user quotes/sources: configuration sprawl, permission schemes, slow, jargon, admin dependency) and what Atlassian changed in 2024–2026 (Jira Work Management merge, new navigation, Rovo). Which patterns explain 'powerful yet simple' (Linear's defaults, Basecamp's constraints, Things 3's calm) versus 'powerful and confusing' (Jira, ClickUp).` },
  { key: 'notion-model-and-block-editors', title: 'Notion data model and block editors',
    brief: `Explain precisely how Notion works under the hood and in UX: blocks, pages-as-blocks, databases with properties/views (table, board, timeline, calendar, gallery, list), relations/rollups/formulas, templates, synced blocks, permissions model, comments, Notion AI, Notion Calendar (ex-Cron), Notion Mail, Notion Sites; its weaknesses (performance, permissions confusion, offline, database limits, hard to govern at scale). Then survey open-source Notion-like editors and engines for building our own block/document layer: Tiptap (v3, and Tiptap Cloud/Hocuspocus), BlockNote, Plate (Slate-based), Lexical, ProseMirror, Milkdown, Editor.js, Yjs/CRDT collaboration, Liveblocks, PartyKit; AFFiNE/AppFlowy/Anytype's block models. Compare license, maturity, collaborative editing support, table/database support, mentions, slash commands, export. Recommend which we should build on and how much of Notion to copy versus deliberately not copy for a government department.` },
  { key: 'all-in-one-suites-lark-bitrix', title: 'All-in-one suites: Lark/Feishu, Bitrix24, Microsoft, Google, Zoho',
    brief: `Study "all-in-one" work suites that unify chat, docs, tasks, calendar, approvals, HR: Lark/Feishu (ByteDance; approvals, OKR, org structure, Base, Docs, meeting, its UX reputation and adoption in Asia and by companies/governments), Bitrix24 (very popular in CIS/Russia/Uzbekistan for CRM+tasks+HR; why it is loved and why it is ugly/cluttered), Microsoft 365/Teams/Loop/Planner/Viva, Google Workspace, Zoho One, Yandex 360, WeCom/DingTalk (government use in China), Slack canvas/lists. What do they get right about a single, integrated system? Where does integration become bloat? Which of them are used by governments in Central Asia/CIS (evidence)? What can we borrow for the 'one place for everything' feeling while keeping first-time simplicity?` },
  { key: 'open-source-foundations', title: 'Open-source foundations and forkable products',
    brief: `Survey open-source products we could build on, fork, or learn from, and list for each: license (AGPL/MIT/Apache etc. and implications for a government fork), tech stack, GitHub stars/activity as of 2026, maturity, self-host story, notable adopters. Candidates: Plane (project mgmt), Huly, AppFlowy, AFFiNE, Anytype, Twenty (CRM), Outline (wiki), OpenProject (used by German gov), Nextcloud (gov adoption in Germany/France/EU), Taiga, Focalboard, Vikunja, Leantime, Kimai, Documenso (e-sign), Cal.com, Formbricks, NocoDB/Baserow/Teable, Directus, Payload CMS, Novu, Postiz, Rallly, Odoo (HR/projects), OrangeHRM, Frappe/ERPNext HR, Mattermost/Rocket.Chat/Zulip. Also government-focused open source: GovStack, X-Road, Tchap (France Matrix), openDesk (Germany's sovereign workplace: Nextcloud+OpenProject+XWiki+Element), Digital Public Goods. Conclude: build-from-scratch vs fork vs compose, with a recommended shortlist and reasons.` },
  { key: 'govtech-and-public-sector-patterns', title: 'GovTech design patterns and how internal gov tools spread',
    brief: `Research public-sector product/design practice and internal-tool adoption: UK GDS Service Manual + GOV.UK Design System (its content principles, one-thing-per-page, patterns), US USWDS + 18F/US Digital Service practices, Singapore GovTech (Design System, Workpal, products for civil servants), Estonia (X-Road, e-Estonia internal tools), Denmark/Finland, EU's openDesk and sovereign workplace, Ukraine's Diia (as a UX benchmark), Kazakhstan's eGov, Russia's Gosuslugi/GosTech. How do internal tools spread across ministries: case studies (Slack from Tiny Speck, Asana from Facebook, Jira at Atlassian, Retool, GovTech Singapore's internal products, GDS Notify/Pay adoption model, 18F). What made them adoptable across agencies: templates, zero-config defaults, shared platform teams, multi-tenancy, public roadmap, champions. Also: civil-servant workflows (document control, instructions from leadership with deadlines, reporting up the hierarchy, protocol/assignments tracking) and how gov tools model 'instruction → executor → deadline → report' (execution control, 'ispolnitelskaya distsiplina').` },
  { key: 'uzbekistan-context', title: 'Uzbekistan context: institutions, systems, law, language, culture',
    brief: `Research everything specific to Uzbekistan that shapes this product: Ministry of Digital Technologies (structure, mandate, key initiatives), "Digital Uzbekistan 2030" strategy, UN EGDI ranking history for Uzbekistan (2018–2024, targets), IT Park, UZINFOCOM, national systems: OneID (id.egov.uz single sign-on: how integration works, OAuth/OIDC?), E-Imzo (digital signature: how it works technically, browser plugin, mobile), ijro.gov.uz (execution-control system for government instructions) and E-Qaror, my.gov.uz, e-hujjat/inter-agency document flow, "Yagona interaktiv davlat xizmatlari portali". Law: personal-data localization requirement (Law on Personal Data 2019, amendments 2021, Article 27-1), information security requirements for state bodies, O'zDSt standards, use of foreign cloud by government bodies (allowed? restrictions), state secrets classification levels. Language: Uzbek Latin script as official, Cyrillic still common, Russian widespread in government; transliteration rules; date formats; names (patronymic usage); Uzbek plural/possessive forms relevant to UI strings; public holidays 2026. Culture: Telegram ubiquity (statistics), how civil servants communicate, hierarchy/formality norms, working hours, reporting cadences, typical instruction-with-deadline workflow ('topshiriq'), the meaning of 'ijro intizomi'. Government hosting options (data centers, gov cloud). Civil service HR: position grades, 'shtat jadvali' (staffing table), attestation, leave rules (Labor Code 2023: 21+ days), sick leave, business trips (komandirovka), timekeeping ('tabel'). Give Uzbek and Russian terms for core UI concepts (task, project, deadline, approval, leave, instruction, report, department, sub-department, employee, meeting).` },
  { key: 'zero-training-ux-and-onboarding', title: 'Zero-training UX: onboarding, defaults, progressive disclosure',
    brief: `Research how to make a powerful tool usable without training: progressive disclosure, sensible defaults, templates, empty states that teach, contextual help, UX writing (plain language, Uzbek/Russian localisation pitfalls), Nielsen's heuristics applied to work tools, "Don't Make Me Think", Jobs-to-be-done for civil servants, time-to-first-value, activation metrics, onboarding checklists, product tours (why most tours fail), keyboard-first patterns with discoverable shortcuts, command palette (cmdk, Linear/Raycast/Notion), search-as-navigation, natural-language quick-add (Todoist/Things/Amie), 'inbox zero' triage patterns, notification design that doesn't overwhelm, digest emails, undo instead of confirm dialogs, optimistic UI, autosave, mobile-first vs desktop-first for office workers, accessibility (WCAG 2.2 AA, keyboard, screen readers, low-vision civil servants), older users and low digital literacy patterns, RTL not needed but Cyrillic/Latin script switching. Case studies: Superhuman onboarding, Slack, Notion templates, Linear onboarding, Figma, Airtable, Duolingo (motivation), GOV.UK content style. Produce a concrete 'first 10 minutes' design for a new civil servant and a 'first 10 minutes' for a department head, with evidence.` },
  { key: 'design-systems-craft-and-motion', title: 'Design systems, visual craft, motion, and delightful apps',
    brief: `Research the state of the art in UI craft for 2025–2026: shadcn/ui (v3? registry, blocks), Radix, Base UI, Ark UI, Tailwind CSS v4, design tokens (W3C DTCG), OKLCH color systems (Linear's LCH approach, Radix Colors, Tailwind v4 oklch palettes), typography systems (Inter, Geist, IBM Plex, fonts with Cyrillic+Latin Uzbek support incl. Uzbek-specific letters Oʻ Gʻ ʼ), dark mode done right, density modes, motion principles (Emil Kowalski's animations course, Rauno Freiberg's craft, Framer Motion/Motion v12, View Transitions API, spring physics, reduced-motion), micro-interactions, skeletons vs spinners, toasts (Sonner), command menus (cmdk), drawers (Vaul), data tables aesthetics, icon sets (Lucide, Phosphor, Hugeicons), illustration/empty-state style, sidebar patterns (collapsible, resizable), layout shells (Linear, Notion, Height, Arc, Raycast, Cron/Notion Calendar, Amie, Things 3, Craft, Family, Vercel, Attio, Campsite, Cal.com). Also: how an 'editorial/institutional' aesthetic (serif headings, warm paper, deep green) can coexist with a fast product UI (see reference audit palette), and examples of governmental products that look premium (Diia, Singapore, GOV.UK vs Estonia). Give a concrete recommended design-token starter (colors in OKLCH, type scale, spacing, radius, elevation, motion durations/easings) and a list of components to build first.` },
  { key: 'data-dense-ui-components', title: 'Data-dense UI components: tables, boards, timelines, calendars, org charts, charts',
    brief: `Survey the best libraries and UX patterns for the heavy components we need, with versions, license, bundle size, virtualization, accessibility and known issues: data tables (TanStack Table v8, AG Grid community/enterprise, Glide Data Grid, react-data-grid, MUI X), virtualized lists (TanStack Virtual, react-window), kanban drag-and-drop (dnd-kit, pragmatic-drag-and-drop by Atlassian, react-beautiful-dnd EOL), Gantt/timeline (Frappe Gantt, SVAR, Bryntum (commercial), gantt-task-react, custom SVG approaches, Linear/Height timeline UX), calendars (Schedule-X, FullCalendar, react-big-calendar, Toast UI; Notion Calendar/Amie UX), org charts (React Flow/xyflow, d3-org-chart, OrgChart JS, ELK/dagre layouts, expanding thousands of nodes), rich charts (Recharts, visx, Nivo, ECharts, Observable Plot, Tremor, shadcn charts), KPI/dashboard UX best practices (what dashboards civil servants actually read), inline editing patterns (Notion/Airtable/Linear cell editing), spreadsheet-like grids, filters/sort/group UIs (Linear's filter bar, Notion's), saved views, bulk actions, keyboard navigation in lists, mobile equivalents of each. Recommend a stack and note where we must build custom.` },
  { key: 'frontend-architecture-and-sync', title: 'Frontend architecture, local-first sync, real-time collaboration',
    brief: `Research the frontend architecture options for a Linear-fast, offline-tolerant, real-time internal tool in 2026: React 19 (server components, actions, compiler), Next.js 15/16 vs Vite + TanStack Router/Start vs Remix/React Router 7; TanStack Query v5; state (Zustand, Jotai, XState); local-first sync engines and their production readiness/licensing: Rocicorp Zero, ElectricSQL (v1+), PowerSync, Replicache (deprecated in favor of Zero?), Jazz, TinyBase, Triplit, Instant DB, Convex, Linear's custom sync engine (talks/blog posts), Figma's multiplayer; CRDTs (Yjs, Automerge, Loro) for documents; real-time via WebSockets/SSE; optimistic updates; conflict handling; permission-aware sync (the hard problem for RBAC apps); PWA/offline for government office networks that drop; bundle/perf budgets (Core Web Vitals for apps), code-splitting; i18n libraries (Lingui, Paraglide/inlang, i18next, next-intl) with plural rules for Uzbek/Russian; date/time (Temporal, date-fns v4, Day.js) with Uzbek locale support; form libraries (react-hook-form, TanStack Form, Conform) + zod v4; testing the frontend. Give a recommended architecture with rationale and the top 5 risks.` },
  { key: 'backend-architecture-and-multitenancy', title: 'Backend architecture, multi-tenancy for many ministries, on-prem deployment',
    brief: `Research backend choices for a multi-tenant government platform that must run on-premise or in a national gov cloud: language/runtime (TypeScript Node/Bun with Hono/Fastify/NestJS vs Go vs .NET vs Elixir/Phoenix; team-hiring reality in Uzbekistan), Postgres 17 as the system of record (row-level security, logical replication, pgvector, partitioning), ORMs (Drizzle vs Prisma vs Kysely), multi-tenancy strategies (shared schema + tenant_id + RLS vs schema-per-tenant vs database-per-tenant vs separate deployments per ministry) with pros/cons for security audits, migrations, noisy neighbours, data-localization compliance, and 'each ministry wants its own instance' politics; event-driven design and audit trails (append-only event log, outbox pattern, event sourcing lite), background jobs (pg-boss, BullMQ/Redis, Temporal/Inngest/Trigger.dev), search (Postgres FTS with Uzbek/Russian stemming, Meilisearch, Typesense, OpenSearch), file storage (MinIO/S3-compatible, virus scanning, previews), email (self-hosted SMTP, Postal, or gov SMTP), realtime (WebSocket gateway, Centrifugo, Soketi), caching (Redis/Valkey/Dragonfly), API style (REST + OpenAPI vs tRPC vs GraphQL, and public API for other ministries' integrations), webhooks, rate limiting, observability (OpenTelemetry, Grafana/Loki/Tempo, Sentry self-hosted), deployment (Docker Compose for a single ministry box, Kubernetes/k3s for scale, Helm, air-gapped installs, offline license/updates), backups/PITR (pgBackRest), DR, upgrades with zero downtime, seeding/tenant provisioning, config/feature flags (OpenFeature, Unleash, Flagsmith). Provide a reference architecture diagram in text and a recommended stack with reasons and risks.` },
  { key: 'auth-permissions-security-compliance', title: 'Identity, permissions, audit and security for a government tool',
    brief: `Research identity and authorization for a government internal platform: SSO via OIDC/SAML, self-hosted IdPs (Keycloak 26, Zitadel, Authentik, Ory), embedded auth libs (Better Auth, Auth.js, Lucia's successor), integrating a national SSO like Uzbekistan's OneID (protocol details if public), SCIM/directory sync (Active Directory/LDAP—common in ministries), passkeys/WebAuthn, MFA policies, session management, device trust; authorization models: RBAC vs ABAC vs ReBAC (Zanzibar-style: OpenFGA, SpiceDB, Permit.io, Casbin, Oso, Cerbos), how Notion/Linear/Google model sharing and how to keep permission UX simple (the 'who can see this' problem), field-level permissions (restricted HR fields), hierarchical org-based permissions (director sees all; head sees unit; employee sees own) and delegation/acting-in-place (deputy while on leave); audit logging (what to log, tamper-evidence, retention, who-viewed-sensitive-data), data classification, encryption at rest/in transit, secrets management, OWASP ASVS 5.0 and Top 10 2025, supply-chain (SBOM, dependency scanning), ISO 27001 controls relevant to an internal tool, national requirements (Uzbek information-security rules for state information systems, certification/attestation of state systems, O'zDSt ISO adaptations), personal-data minimization, right-to-access logs, and secure-by-default deployment checklists. Give a permission model proposal (roles, scopes, object-level sharing, field tiers) simple enough to show in one screen.` },
  { key: 'hr-people-ops-features', title: 'People & HR operations features civil servants need',
    brief: `Research HRIS and people-ops features and their best UX: BambooHR, Rippling, Personio, HiBob, Deel, Lattice, 15Five, Leapsome, Workday (as anti-pattern), Factorial, Gusto; open-source OrangeHRM, Frappe HR, Odoo HR. Features: employee record (public profile vs restricted), org chart with dotted lines and vacancies, positions/staffing table ('shtat'), onboarding/offboarding checklists, leave/time-off requests and approvals with balances and calendars, attendance/timesheets/tabel, business trips, sick leave, remote-work days, 1:1s, OKRs/goals, performance reviews/attestation, skills matrix and certifications, training/learning plans, succession, capacity/workload views, birthdays/anniversaries, kudos/recognition, surveys/pulse, exit. Which of these matter in a government department (evidence from public-sector HR practice, Uzbek civil-service rules: attestation, ranks, leave 21+ days under 2023 Labor Code, komandirovka orders), which create bureaucracy, and how to present them so an employee needs zero training (e.g., 'request leave' in 3 clicks with balance shown, manager approves from notification). Include a data model sketch for the employee/position/unit/leave entities.` },
  { key: 'documents-approvals-and-workflows', title: 'Documents, meeting notes, approvals, e-signature, official correspondence',
    brief: `Research document and workflow features: knowledge bases/wikis (Confluence, Notion, Outline, Slite, GitBook, XWiki), meeting notes with action items (Notion, Granola, Fellow, Otter), decision records/ADR practice, templates, version history and diff, comments/mentions, document review/approval flows (Lark Approval, Kissflow, Jira Service Management approvals, Pipefy, ProcessMaker, n8n/Temporal-driven flows, Camunda), e-signature (Documenso, DocuSign; Uzbekistan's E-Imzo legal digital signature and how gov docs are signed), official correspondence/registry systems used in CIS governments (Directum, ELMA365, 1C:Document Management, Bitrix24, Docsvision, Uzbek e-hujjat/ijro.gov.uz) and the 'instruction → executor → deadline → report → closure' pattern (execution control), incoming/outgoing letter registration numbers, protocol of meetings with assignments, form builders (Typeform, Tally, Formbricks, Fillout) for internal requests, file management (folders vs tags, previews, Office file editing via OnlyOffice/Collabora, PDF), templates for common government documents (memo, official letter, protocol, order, report, business-trip order), and how to make approvals feel like one tap. Recommend which workflows to build natively vs integrate, and a minimal workflow engine design (states, steps, SLAs, escalations).` },
  { key: 'portfolio-pm-analytics-dashboards', title: 'Portfolio management, status reporting, KPIs/OKRs, analytics dashboards',
    brief: `Research how organisations track many initiatives without heavy PMO overhead: status-report cadences (weekly updates in Linear/Asana/Height, Basecamp Hill charts, Range, Standuply), portfolio health scoring (on track/at risk/blocked semantics, RAG, confidence), roadmaps (Linear initiatives, Productboard, Aha!, Airfocus), OKR systems (Lattice, Perdoo, Quantive, Profit.co; OKR failure modes in government), KPI dashboards (Geckoboard, Databox, Metabase, Grafana; what executives actually read), dependency and risk registers, delay prediction/alerts, capacity/workload views (Float, Resource Guru, Asana Workload), time-based views, weekly digest emails/Telegram summaries, executive one-pagers, government PMO practices (UK IPA, Malaysia PEMANDU delivery labs, Indonesia, UAE government performance systems, Uzbekistan's KPI systems for ministries if any), reporting-up-the-hierarchy patterns (unit → department → ministry → Cabinet), evidence-based dashboard design (Stephen Few, Edward Tufte, Google's dashboard guidance), and the anti-patterns (vanity metrics, red-status fear, gaming). Propose our portfolio/status model: objects, fields, rituals, escalations, and the 3 dashboards worth building first.` },
  { key: 'ai-features-and-assistants', title: 'AI features in work tools and safe AI for government',
    brief: `Research AI capabilities in work tools as of 2026 and how to do them well: Notion AI (Q&A over workspace, autofill, meeting notes), Linear (AI triage, agents in issues), Asana AI Studio, ClickUp Brain, Slack AI, Lark AI, Microsoft Copilot in Teams/Planner, Atlassian Rovo, Coda AI, Airtable AI, Granola. Patterns: summarize threads/projects, draft status updates from activity, natural-language search and filters, quick-add parsing, meeting-notes-to-actions, weekly digest generation, translation Uzbek↔Russian↔English (quality of current models for Uzbek Latin/Cyrillic), document drafting in official style, Q&A over the workspace (RAG), anomaly/delay detection, 'ask the org' (who knows X), agents that execute workflows (with MCP—Model Context Protocol—and Anthropic's Claude Agent SDK). Safety/governance: data residency for LLM calls (can a Uzbek ministry send data to a foreign API? options: on-prem open-weight models like Llama/Qwen/Gemma, local inference with vLLM/Ollama, Uzbek language capability of open models, national LLM efforts in Uzbekistan), prompt-injection risks in workspace-RAG tools, permission-aware retrieval, audit of AI actions, human-in-the-loop for approvals, evaluation methods, cost control, and what NOT to do (AI slop, hallucinated summaries in official reporting). Recommend an AI feature ladder (phase 1 safe wins → phase 3 agents) and an architecture that can switch between Claude API and an on-prem model.` },
  { key: 'notifications-telegram-mobile', title: 'Notifications, Telegram integration, mobile and offline',
    brief: `Research notification and mobile strategy: notification design principles (batching, digests, quiet hours, per-object subscriptions, inbox/triage UX like Linear's inbox and GitHub notifications), notification infrastructure (Novu, Knock, Courier, self-hosted options), email deliverability inside gov networks, Telegram as a channel: Bot API capabilities (inline buttons for approve/decline, deep links, login widget, Telegram Login/WebApp auth), Telegram Mini Apps (TMA) as a mobile client for civil servants (capabilities, limits, auth, offline, examples of gov/enterprise mini apps, Uzbek gov bots), security considerations of Telegram for official data (what should never be sent), alternative national messengers, SMS gateways in Uzbekistan (Eskiz, Playmobile), push via web push/PWA on iOS/Android, native app vs PWA vs Capacitor/Expo for a phase-2 mobile app, offline patterns for field/weak-network use, calendar integration (CalDAV, Google/Outlook) for meetings and leave, and 'do not disturb' cultural norms in government (evening/weekend messages from bosses). Recommend a notification model (events → preferences → channels → digests) and a Telegram integration plan with concrete bot commands and mini-app screens.` },
  { key: 'engineering-quality-and-agentic-delivery', title: 'Engineering quality, testing, delivery process, and agentic coding best practices',
    brief: `Research two things. (A) Engineering quality for a robust internal platform: testing pyramid for React+Node (Vitest, Playwright E2E, component tests, contract tests, Storybook + visual regression via Chromatic/Argos/Lost Pixel/Playwright screenshots), accessibility testing (axe), performance budgets and Lighthouse CI, database migration safety (Drizzle/Prisma migrations, expand-contract), seeding/fixtures/demo tenants, CI/CD (GitHub Actions/GitLab CI self-hosted for gov), release trains and changelogs, feature flags, error tracking, i18n QA (pseudo-localization, missing-key detection), security scanning (Semgrep, Trivy, npm audit), load testing (k6). (B) Agentic software delivery best practices in 2026 for shipping a large product with AI coding agents end to end: Claude Code subagents/hooks/skills/workflows patterns, Anthropic's guidance on agentic coding, spec-driven development (Kiro-style specs, PRD → tech spec → tasks), the 'Ralph Wiggum loop' / autonomous loops with completion criteria, test-driven agent loops, reviewer/verifier separation, how to avoid infinite approve/redo cycles (bounded retries, escalation to human only on genuine ambiguity, deterministic gates, 'definition of done' checklists, acceptance criteria written before code), context management (CLAUDE.md/AGENTS.md conventions, progress ledgers, ADRs), worktree isolation for parallel agents, evals for agent output, common failure modes (scope creep, hallucinated APIs, tests that assert nothing, silent skipping, 'looks done' syndrome, agents editing tests to pass), and metrics for agentic delivery. Produce a recommended QA gate list and a recommended agent-loop design with explicit stop conditions.` },
]

const RESEARCH_SCHEMA = {
  type: 'object',
  properties: {
    key: { type: 'string' },
    file_path: { type: 'string' },
    word_count_estimate: { type: 'number' },
    sources_count: { type: 'number' },
    headline_insights: { type: 'array', items: { type: 'string' }, description: '5-10 most important, specific insights' },
    top_recommendations: { type: 'array', items: { type: 'string' }, description: 'the ADOPT/ADAPT/AVOID recommendations, one line each' },
    open_questions: { type: 'array', items: { type: 'string' } },
  },
  required: ['key', 'file_path', 'headline_insights', 'top_recommendations', 'open_questions'],
}

const CRITIC_SCHEMA = {
  type: 'object',
  properties: {
    key: { type: 'string' },
    coverage_score: { type: 'number', description: '0-10 how completely the brief was covered' },
    evidence_score: { type: 'number', description: '0-10 how well claims are sourced and verified' },
    gaps: { type: 'array', items: { type: 'string' }, description: 'specific missing topics from the brief or obvious adjacent topics' },
    corrections: { type: 'array', items: { type: 'string' }, description: 'claims that were wrong or unverifiable after spot-check' },
    needs_gap_fill: { type: 'boolean' },
  },
  required: ['key', 'coverage_score', 'evidence_score', 'gaps', 'corrections', 'needs_gap_fill'],
}

phase('Research')
log(`Fanning out ${DIMENSIONS.length} research agents`)

const researched = await pipeline(
  DIMENSIONS,
  // Stage 1: research + write file
  (d) => agent(
    `${CONTEXT}\n\nYOUR DIMENSION: "${d.title}" (key: ${d.key})\n\nBRIEF:\n${d.brief}\n\n${RESEARCH_RULES}\n\nWrite the report to: ${RESEARCH_DIR}/${d.key}.md\nTitle the document "# ${d.title}" and start with a 5-line TL;DR.`,
    { label: `research:${d.key}`, model: 'sonnet', phase: 'Research', schema: RESEARCH_SCHEMA, agentType: 'general-purpose', effort: 'high' }
  ),
  // Stage 2: critic + spot-check
  (r, d) => agent(
    `${CONTEXT}\n\nYou are a demanding research editor. A researcher was given this brief for dimension "${d.title}":\n${d.brief}\n\nRead their report at ${RESEARCH_DIR}/${d.key}.md (use Read). Then:\n1. List every topic in the brief that is missing, thin, or hand-waved, plus 2-4 adjacent topics a senior product/engineering lead would expect and that are absent.\n2. Spot-check 5 of the most consequential factual claims (licenses, versions, capabilities, numbers, legal facts) with WebSearch/WebFetch. Record which were confirmed, which were wrong, which unverifiable.\n3. Append a section "## Editor's verification notes (${d.key})" to the SAME file (Read it, then Write the full file back with the section appended; do not delete existing content) listing confirmations, corrections and gaps.\n4. Return the structured verdict. Set needs_gap_fill=true if coverage_score < 8 or there are 3+ gaps or any correction is material.`,
    { label: `critic:${d.key}`, model: 'sonnet', phase: 'Verify', schema: CRITIC_SCHEMA, agentType: 'general-purpose', effort: 'medium' }
  ).then(v => ({ research: r, verdict: v })),
  // Stage 3: gap fill if needed
  async (x, d) => {
    if (!x || !x.verdict) return x
    if (!x.verdict.needs_gap_fill) return x
    const fill = await agent(
      `${CONTEXT}\n\nDimension "${d.title}" (key: ${d.key}). The report at ${RESEARCH_DIR}/${d.key}.md was reviewed and found to have these GAPS:\n- ${x.verdict.gaps.join('\n- ')}\n\nand these CORRECTIONS:\n- ${(x.verdict.corrections || []).join('\n- ') || '(none)'}\n\nYour job: research ONLY the gaps (at least 6 WebSearch queries and 4 WebFetch reads), fix the corrections in place, and append a section "## Gap-fill addendum" with the new material (same quality bar: specific, sourced, opinionated, with [ADOPT]/[ADAPT]/[AVOID] recommendations). Read the file, then Write the complete updated file back. Add new sources to the Sources list.`,
      { label: `gapfill:${d.key}`, model: 'sonnet', phase: 'Verify', schema: RESEARCH_SCHEMA, agentType: 'general-purpose', effort: 'high' }
    )
    return { ...x, gapfill: fill }
  }
)

const done = researched.filter(Boolean)
log(`Research complete: ${done.length}/${DIMENSIONS.length} dimensions; gap-filled: ${done.filter(x => x.gapfill).length}`)
const dropped = DIMENSIONS.filter((d, i) => !researched[i]).map(d => d.key)
if (dropped.length) log(`WARNING dropped dimensions (agent died): ${dropped.join(', ')}`)

phase('Matrix')
const matrix = await agent(
  `${CONTEXT}\n\nAll research reports are in ${RESEARCH_DIR}/*.md (list them with Glob/Bash, read all of them). Produce ${RESEARCH_DIR}/competitive-matrix.md: \n1. A feature matrix table: rows = capabilities (at least 40: e.g. tasks, subtasks, projects, initiatives/goals, weekly status updates, kanban, timeline/gantt, calendar, docs/wiki, block editor, databases/custom fields, approvals, e-sign, leave, org chart, directory privacy tiers, inbox/notifications, Telegram, command palette, keyboard-first, offline, mobile, search, AI summaries, audit log, RBAC granularity, SSO, multi-tenant, self-host, i18n incl. Uzbek/Russian, templates, forms, files, meeting notes, OKR, dashboards, time tracking, events/RSVP, recognition...); columns = Jira, Linear, Notion, Asana, ClickUp, Monday, Lark, Bitrix24, Plane, Huly, OpenProject, AppFlowy/AFFiNE, our reference prototype. Cells: ✅ strong / 🟡 partial / ❌ none / ? unknown, with short notes where useful.\n2. A second table: 'Loved / Hated' one-liners per product with source.\n3. 'White space' section: capabilities nobody does well for a government department (be specific and evidence-based).\n4. 'Complexity budget' section: for each capability, estimate UX-complexity cost (Low/Med/High) and value for our department (Low/Med/High) so the plan can pick high-value/low-complexity first.\nWrite the file; return a summary.`,
  { label: 'competitive-matrix', model: 'sonnet', phase: 'Matrix', agentType: 'general-purpose', effort: 'high',
    schema: { type: 'object', properties: { file_path: { type: 'string' }, white_space: { type: 'array', items: { type: 'string' } }, high_value_low_complexity: { type: 'array', items: { type: 'string' } } }, required: ['file_path', 'white_space', 'high_value_low_complexity'] } }
)

phase('Vision')
const LENSES = [
  { key: 'civil-servant-daily-life', prompt: `LENS: THE SPECIALIST'S DAY. You are a brilliant product designer who has spent a year sitting next to specialists and unit heads in a Tashkent ministry. Design the product around the hour-by-hour reality of a specialist and a head of sub-department: instructions arriving from above with deadlines, Friday reporting, Telegram chaos, documents needing approval, leave requests, meetings with protocols, EGDI evidence gathering. Optimize for 'makes my day better' and zero training. Be concrete about screens, defaults, and what the product refuses to do.` },
  { key: 'director-governance-robustness', prompt: `LENS: THE DIRECTOR AND THE INSTITUTION. You are a former GovTech platform lead who scaled an internal tool across 20 agencies. Design for the director/minister view, execution discipline (ijro intizomi), accountability, audit, privacy tiers, multi-tenancy across ministries, integrations with OneID/E-Imzo/ijro.gov.uz, data localization, operational robustness, and the politics of adoption across ministries. Optimize for 'this can become the standard' while staying simple for end users. Be concrete about the tenant model, permission model, rituals, and what must be true before another ministry can adopt it in a day.` },
  { key: 'craft-and-delight', prompt: `LENS: CRAFT AND DELIGHT. You are the design lead behind a product famous for its taste (think Linear, Things, Craft, Notion Calendar). Design for the feeling: speed, keyboard and command palette, motion that explains, an editorial-institutional visual identity (evolve the reference's warm paper + deep green + serif headings into something distinctive and modern), calm notifications, the 'wow' moments that make civil servants show it to friends in other ministries, and the 'no' list (features and clutter you refuse). Optimize for 'goes viral because it feels wonderful' without sacrificing power. Be concrete about the interaction model, the top 10 signature interactions, the design-token direction, and how uniqueness to Uzbekistan shows in the design (language, calendar, names, culture) without kitsch.` },
]

const VISION_SCHEMA = {
  type: 'object',
  properties: {
    lens: { type: 'string' },
    file_path: { type: 'string' },
    one_sentence_thesis: { type: 'string' },
    signature_ideas: { type: 'array', items: { type: 'string' }, description: '8-12 distinctive ideas that are NOT generic' },
    refused_features: { type: 'array', items: { type: 'string' } },
  },
  required: ['lens', 'file_path', 'one_sentence_thesis', 'signature_ideas', 'refused_features'],
}

const visions = (await parallel(LENSES.map(l => () => agent(
  `${CONTEXT}\n\n${l.prompt}\n\nINPUTS: Read ${AUDIT}, then read ALL files in ${RESEARCH_DIR}/ (there are ~19 reports incl. competitive-matrix.md; read every one fully, they are your evidence base). Then write ${SYNTH_DIR}/vision-${l.key}.md (2,000–3,500 words) with these sections: 1) Thesis (one paragraph). 2) Who it is for and their day (short vignettes). 3) The object model (what things exist: e.g. instruction/task, project, initiative, document, person, unit, request, event; how they relate; keep it small). 4) Feature plan by phase (Phase 1 'first 90 days' must be shippable and already better than the reference; Phase 2; Phase 3) — each feature with a one-line 'why' and a 'zero-training test' (how a first-time user discovers it). 5) Signature interactions (10). 6) What we refuse to build and why. 7) Uniqueness to Uzbekistan / this ministry. 8) Risks and how the plan avoids Jira-syndrome and ClickUp-bloat. 9) A candid critique of the reference prototype. Write with taste and conviction; no bullet-salad, no generic AI phrasing, no hedging. Cite research files where a claim depends on evidence (e.g. [see auth-permissions-security-compliance.md]).`,
  { label: `vision:${l.key}`, model: 'opus', phase: 'Vision', schema: VISION_SCHEMA, agentType: 'general-purpose', effort: 'xhigh' }
)))).filter(Boolean)

log(`Vision drafts written: ${visions.map(v => v.lens).join(', ')}`)

phase('Judge')
const JUDGE_SCHEMA = {
  type: 'object',
  properties: {
    judge: { type: 'string' },
    scores: { type: 'array', items: { type: 'object', properties: { lens: { type: 'string' }, simplicity: { type: 'number' }, power: { type: 'number' }, uniqueness: { type: 'number' }, feasibility: { type: 'number' }, taste: { type: 'number' }, total: { type: 'number' }, verdict: { type: 'string' } }, required: ['lens', 'total', 'verdict'] } },
    best_ideas_to_graft: { type: 'array', items: { type: 'string' }, description: 'specific ideas from any draft that MUST survive into the final plan, with the source lens' },
    ideas_to_kill: { type: 'array', items: { type: 'string' }, description: 'ideas that are generic, infeasible, or bloat, with reason' },
    file_path: { type: 'string' },
  },
  required: ['judge', 'scores', 'best_ideas_to_graft', 'ideas_to_kill', 'file_path'],
}
const JUDGES = [
  { key: 'first-time-user', prompt: 'You are a 24-year-old specialist who just joined the ministry and a 52-year-old head of sub-department who dislikes new software. Judge each draft by whether you would understand and love it in the first 10 minutes without training, and whether it removes real pain from your week.' },
  { key: 'staff-engineer', prompt: 'You are a staff engineer who has shipped multi-tenant government systems. Judge each draft for feasibility in a 90-day phase 1 with a small team + AI agents, architectural soundness, security/privacy realism, and whether the object model will survive contact with 20 ministries.' },
  { key: 'design-critic', prompt: 'You are a merciless design critic with taste (you admire Linear, Things, GOV.UK content design, and Diia). Judge each draft for coherence of interaction model, restraint, distinctiveness, and whether it would make people in other ministries ask for access. Punish generic AI-sounding ideas and feature lists without a point of view.' },
]
const judgments = (await parallel(JUDGES.map(j => () => agent(
  `${CONTEXT}\n\n${j.prompt}\n\nRead the three drafts in ${SYNTH_DIR}/vision-*.md (all of them, fully) and skim ${RESEARCH_DIR}/competitive-matrix.md. Score each draft 0–10 on simplicity, power, uniqueness, feasibility, taste (total = sum, max 50) with a two-sentence verdict each. Then list the specific ideas that MUST be grafted into the final plan regardless of which draft wins, and the ideas that must be killed. Write your full critique to ${SYNTH_DIR}/judge-${j.key}.md and return the structured result.`,
  { label: `judge:${j.key}`, model: 'sonnet', phase: 'Judge', schema: JUDGE_SCHEMA, agentType: 'general-purpose', effort: 'high' }
)))).filter(Boolean)

const totals = {}
for (const j of judgments) for (const s of j.scores) totals[s.lens] = (totals[s.lens] || 0) + (s.total || 0)
const ranked = Object.entries(totals).sort((a, b) => b[1] - a[1])
log(`Judge totals: ${ranked.map(([l, t]) => `${l}=${t}`).join(', ')}`)
const winner = ranked[0] ? ranked[0][0] : (visions[0] && visions[0].lens)
const grafts = judgments.flatMap(j => j.best_ideas_to_graft)
const kills = judgments.flatMap(j => j.ideas_to_kill)

phase('Synthesize')
const synthesis = await agent(
  `${CONTEXT}\n\nYou are the product lead making the final call. The judge panel ranked the vision drafts: ${ranked.map(([l, t]) => `${l} (${t}/150)`).join(', ')}. Winner: ${winner}.\n\nIdeas that MUST survive (from judges):\n- ${grafts.join('\n- ')}\n\nIdeas to KILL:\n- ${kills.join('\n- ')}\n\nRead: ${AUDIT}; all three ${SYNTH_DIR}/vision-*.md; all three ${SYNTH_DIR}/judge-*.md; ${RESEARCH_DIR}/competitive-matrix.md; and skim the other research reports as needed for evidence.\n\nWrite ${SYNTH_DIR}/feature-plan-draft.md containing:\n1. 'The plan in four paragraphs' — exactly 4 paragraphs, 120–200 words each, written with human taste and conviction (no bullets, no headers inside, no AI phrasing, no hedging): (a) what it is and the core idea that makes it both powerful and simple, (b) phase 1 — what ships first and why it already beats the reference and Jira/Notion for this department, (c) phases 2–3 — how it grows into the department operating system and spreads to other ministries, (d) what we refuse to build, the taste rules, and the risks we are consciously taking.\n2. 'Object model' — a compact table of the core objects and relations.\n3. 'Feature inventory by phase' — a table: feature | phase | why | zero-training test | complexity | evidence file.\n4. 'Signature interactions' — 10, each 1–2 lines.\n5. 'Non-goals and refusals'.\n6. 'Open decisions for the product owner' — questions whose answers change the plan (e.g. OneID availability, on-prem vs gov cloud, Telegram policy, language default).\n7. 'Recommended stack (provisional)' with one line of rationale per choice, referencing research files.\nReturn the four paragraphs verbatim in the structured output.`,
  { label: 'synthesis', model: 'opus', phase: 'Synthesize', agentType: 'general-purpose', effort: 'xhigh',
    schema: { type: 'object', properties: { file_path: { type: 'string' }, four_paragraphs: { type: 'array', items: { type: 'string' } }, open_decisions: { type: 'array', items: { type: 'string' } } }, required: ['file_path', 'four_paragraphs', 'open_decisions'] } }
)

return {
  research: done.map(x => ({ key: x.research && x.research.key, coverage: x.verdict && x.verdict.coverage_score, evidence: x.verdict && x.verdict.evidence_score, gapfilled: !!x.gapfill, insights: x.research && x.research.headline_insights, open_questions: x.research && x.research.open_questions })),
  dropped,
  matrix,
  visions,
  judgments: judgments.map(j => ({ judge: j.judge, scores: j.scores })),
  ranked,
  synthesis,
}