export const meta = {
  name: 'side-tracks',
  description: 'Two isolated tracks that can run beside the v1.1 verification without touching its files: operations completion (EPIC-020: install guide, restore drill, update channel, k3s option, runbooks) and the demo story (a richer, believable demo seed plus a management demo script in four locales). Each in its own worktree; merged later.',
  whenToUse: 'While the main pipeline occupies master. args: {ts, tracks: ["ops-complete","demo-story"]}.',
  phases: [{ title: 'Side tracks', detail: 'ops-complete and demo-story in parallel worktrees on st/<key>' }],
}
const ROOT = 'C:/Users/rpwal/Documents/Work/eGov/WorkPortal'
const WT = (k) => `${ROOT}/.claude/worktrees/st-${k}`
const DONE = { type: 'object', properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, branch: { type: 'string' }, commits: { type: 'number' }, summary: { type: 'string' }, gates_green: { type: 'boolean' }, notes: { type: 'string' } }, required: ['status', 'summary'] }
const CTX = `Devon (WorkPortal): self-hosted department work-tracking platform for a ministry department in Uzbekistan (uz-Latn default, uz-Cyrl, ru, en; roles super_admin, head, member). Read CLAUDE.md first (tooling requirements: ToolSearch "select:LSP" then the LSP tool for TypeScript symbols; chrome-devtools/playwright MCPs for browser work), then docs/03-plan/TECH-SPEC.md §13–§14, MODULE-GUIDE.md (demo logins), agentic/HARDENING.md, agentic/INVARIANTS.md. Another agent is verifying and fixing master at the same time: you work ONLY in your worktree and ONLY in the paths your task allows; never touch master. Commit early and often; before finishing run node agentic/scripts/gate.mjs --profile fast in your worktree and make it green. Return JSON matching the schema.`
const tracks = [
  { key: 'ops-complete', paths: 'docs/ops/**, infra/** (compose, Caddy, backup, sentinel, k3s), tools/backup/**, scripts/** (install/update scripts), README.md operations section, .github/workflows only for a restore-drill job', prompt: `TRACK ops-complete — EPIC-020 and the open ops items of HARDENING (H18, H19, H20 remainder). Deliver, fully working, not described: (1) docs/ops/INSTALL.md — installing WorkPortal on another ministry server from zero: Ubuntu 24.04 host, Docker Engine + Compose, the production compose (infra/), Caddy with a real domain and automatic TLS, the .env from .env.example with every variable explained (AI_API_KEY, TELEGRAM_BOT_TOKEN, TELEGRAM_BOT_USERNAME, TELEGRAM_WEBHOOK_SECRET, storage, backups), first boot, migrations, the /setup super-admin ceremony, smoke checks; a scripts/install.sh that does the reproducible parts idempotently; (2) restore drill: tools/backup/restore-drill.mjs that restores the latest Postgres backup and the MinIO mirror into a scratch database/bucket, runs migrate:verify and a row-count comparison, and writes a report; run it for real against the dev containers and commit the report under agentic/ledger/hardening/2026-09-08T06-45-00-05-00/restore-drill.md; wire a weekly job (compose or cron) and a quarterly drill checklist; (3) docs/ops/UPDATE.md — the update channel: how a department upgrades (image tags or git tag, backup first, migrations before rollout with backward compatibility, health gating, rollback), with scripts/update.sh; (4) infra/k3s/ — a k3s option: manifests (or a Helm-lite kustomization) for api, worker, web, Postgres (or an external DB note), Valkey, MinIO, Centrifugo, Caddy/ingress with cert-manager, with a README and a dry-run validation (kubectl apply --dry-run=client if kubectl is available, else document); (5) docs/ops/RUNBOOK.md — runbooks with exact commands: restart, rotate secrets, restore, pause and resume, wipe (sentinel), Telegram webhook setup, AI endpoint outage, disk full, certificate renewal, an incident template; (6) a docs/ops/CHECKLIST-GO-LIVE.md for the first ministry deployment. Everything in English with a uz-Latn summary at the top of each document. Report branch "st/ops-complete".` },
  { key: 'demo-story', paths: 'packages/db/src/seed/** (demo data only), docs/DEMO-SCRIPT.md, docs/demo/** (screenshots), packages/i18n/messages/modules/demo/** if a demo chip needs text', prompt: `TRACK demo-story — the CTO must show the product to non-technical management, so the demo must tell a believable story of one ministry department's week, and a script must walk a presenter through it. Deliver: (1) the demo seed becomes one coherent story: "Raqamli xizmatlar boshqarmasi", 3 bo'limlar, 12–16 named people with realistic Uzbek names, titles and photos (open-licence avatars or generated initials), a head, two bo'lim boshliqlari as unit roles, one newcomer mid-onboarding; a quarter of work with 4 projects (one slipping, one on track, one done, one just started) with milestones, objective and subjective tasks; 60–90 cards with a realistic spread of statuses, priorities, estimates, dependencies, labels, comments with mentions, checklists, a recurring card, cards from templates; two department goals with targets; two automation rules with a run log; custom fields (two person fields with most values filled and one pending notify-to-fill; one card field); events: a past subbotnik with photos and feedback, an upcoming seminar with RSVPs, a carpool and a poll, a training with a waitlist; inbox items for each persona that make sense on login; personal workspaces for the head and the member with a sprint, tasks, a note and a Pomodoro log; analytics that show real trends (backfill analytics_daily for the last 12 weeks so charts are not empty on first boot); AI traces so the head's AI screen shows spend; join requests pending for the head; everything in natural uz-Latn with correct oʻ/gʻ and no test strings; seed:reset + seed:demo idempotent, test:seed-idempotence green, migrate:verify untouched. (2) docs/DEMO-SCRIPT.md — a 12-minute presenter script in four locales (uz-Latn first): the story, who to log in as at each step, exactly which screens to open and what to click, what to say, the "wow" moments (board drag, celebration on done, head dashboard drill-down, notify-to-fill reaching Telegram, AI briefing, Mini App), and a 3-minute short version; plus docs/demo/ screenshots captured from the running app for each step (boot pnpm start --demo on free ports in your worktree; chrome-devtools MCP). Report branch "st/demo-story".` },
]
phase('Side tracks')
const setup = await agent(`In ${ROOT}: for each key in [${tracks.map(t => t.key).join(', ')}]: if "${WT('x').replace('st-x', 'st-<key>')}" exists leave it; else git worktree add "${ROOT}/.claude/worktrees/st-<key>" -b st/<key> master (if branch st/<key> exists, git branch -f st/<key> master first, then add without -b); then cp "${ROOT}/.env" into the new worktree (gitignored; never print it). Return {"status":"DONE","summary":"<git worktree list>"}.`, { label: 'worktrees', phase: 'Side tracks', agentType: 'general-purpose', model: 'opus', effort: 'medium', schema: DONE })
log(`worktrees: ${setup ? setup.summary.slice(0, 200) : 'died'}`)
const results = await parallel(tracks.map(t => () => agent(`${CTX}\n\nYOUR WORKING COPY IS A GIT WORKTREE AT ${WT(t.key)} ON BRANCH st/${t.key}. Every Bash command must start with: cd "${WT(t.key)}" && … ; absolute paths under ${WT(t.key)} for Read/Edit/Write; never read or edit files under ${ROOT}/apps, ${ROOT}/packages, ${ROOT}/infra or ${ROOT}/docs directly. First: cd "${WT(t.key)}" && pnpm install --prefer-offline. You may edit ONLY: ${t.paths}. Use your own database name via DATABASE_URL/MIGRATION_DATABASE_URL (the shared Docker Postgres is fine) and free ports.\n\n${t.prompt}`, { label: `st:${t.key}`, phase: 'Side tracks', agentType: 'general-purpose', model: 'opus', effort: 'high', schema: DONE })))
for (let i = 0; i < tracks.length; i++) log(`${tracks[i].key}: ${results[i] ? results[i].status : 'died'} — ${results[i] ? results[i].summary.slice(0, 200) : ''}`)
return results.map((r, i) => ({ key: tracks[i].key, status: r && r.status }))
