export const meta = {
  name: 'ui-blitz',
  description: 'UI/UX overhaul: open-source reference research, a design-system + shell foundation with a full motion catalogue, then every screen rebuilt in parallel worktrees to Jakob\'s-Law conventions, merged, booted, screenshotted, critiqued and fixed.',
  whenToUse: 'Run after the product is functionally complete. args: {ts, stage: "research"|"build"|"polish"|"all", skipFoundation, continue, areas: [keys]}.',
  phases: [
    { title: 'Research', detail: 'three reference sweeps → docs/03-plan/ui-references/*.md' },
    { title: 'Foundation', detail: 'motion catalogue, upgraded primitives, new shell, DESIGN.md v2 — on master' },
    { title: 'Worktrees', detail: 'one worktree per area on ui/<area>' },
    { title: 'Wave', detail: 'six areas rebuilt in parallel' },
    { title: 'Merge', detail: 'merge ui/* branches, promote shared components, gates' },
    { title: 'Integrate', detail: 'boot, click through, fix, Playwright screenshot matrix' },
    { title: 'Critique', detail: 'design lead reviews every screenshot and the live app' },
    { title: 'Fix', detail: 'top issues fixed, re-captured, report' },
  ],
}

const TS = (args && args.ts) || 'unstamped'
const STAGE = (args && args.stage) || 'all'
const ROOT = 'C:/Users/rpwal/Documents/Work/eGov/WorkPortal'
const LEDGER = `agentic/ledger/ui-blitz/${TS.replace(/[:+]/g, '-')}`
const WT = (key) => `${ROOT}/.claude/worktrees/ui-${key}`
const run = (s) => STAGE === 'all' || STAGE === s

const CTX = `You are working on Devon (WorkPortal), a self-hosted department work-tracking platform for a ministry department in Uzbekistan: React 19 + Vite 8 + Tailwind v4 web app in apps/web, design system in packages/ui (Radix + cva + cmdk + sonner + vaul + lucide), i18n via per-module message files (uz-Latn default, uz-Cyrl, ru, en; see MODULE-GUIDE.md "i18n messages"), Fastify API in apps/api, Postgres via Docker (pnpm start --demo boots everything with a fully seeded demo department; read scripts/start.mjs for the port env vars so you can boot on free ports). Binding documents: docs/03-plan/UI-OVERHAUL.md (this pass: principles, Jakob's Law map, motion catalogue, areas, definition of done), DESIGN.md (tokens, type, motion tokens, components, states, copy rules), docs/03-plan/ui-references/*.md (verified open-source references, when present), docs/03-plan/FEATURE-PLAN.md (taste rules and refusals).
RULES: tokens only (no raw colours, no ad-hoc shadows or font sizes); every string through i18n in ALL FOUR locales (uz-Latn, uz-Cyrl, ru, en) in the message files you own; every screen keeps designed empty / loading / error / no-permission states; prefers-reduced-motion replaces motion with a crossfade, never removes feedback; keyboard reachable; no hard-coded text (the i18n gate scans JSX); pin exact versions when adding a dependency and keep the main bundle under the budget in agentic/gates.json (lazy-load heavy pieces). Look at your own work in the in-app browser (mcp__Claude_Browser__navigate, screenshot at 1440 and 390 wide, light and dark via the theme toggle or data-theme, uz-Latn and ru) and iterate until it genuinely looks like the reference products — you are the taste. Commit early and often with messages "ui: <what a user now sees>". Before finishing run node agentic/scripts/gate.mjs --profile fast and make it green (typecheck, lint, unit, i18n, secrets); run pnpm --filter @devon/web build once to be sure the bundle builds. Return a JSON result matching the schema.`

const DONE = { type: 'object', properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, branch: { type: 'string' }, commits: { type: 'number' }, summary: { type: 'string' }, routes: { type: 'array', items: { type: 'string' } }, gates_green: { type: 'boolean' }, notes: { type: 'string' } }, required: ['status', 'summary'] }
const mk = (label, phase, prompt, extra) => agent(`${CTX}\n\n${prompt}`, { label, phase, agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: DONE, ...(extra || {}) })

// ---------- Research ----------
const research = [
  { key: 'shell-and-navigation', prompt: `Study, with WebFetch on real pages and repositories (GitHub READMEs, docs, live demos): Huly (hcengineering/platform), Plane (makeplane/plane), Twenty (twentyhq/twenty), cal.com, Linear's public docs/changelog screenshots, Vercel dashboard docs, Raycast/cmdk demos, shadcn/ui blocks (sidebar, dashboard, settings), Magic UI, Origin UI. Extract for OUR screens: shell layout (sidebar structure, collapse behaviour, active state, counts, department switcher), top bar (quick-add, search, inbox bell, avatar menu), page header pattern, settings layout, command palette sections and keyboard model, shortcuts overlay, auth screens, empty states, toasts. For each: what the convention is (Jakob's Law), a concrete spec (sizes, spacing, behaviour), and which open-source code we can adapt with its licence and exact package version.` },
  { key: 'boards-lists-calendars', prompt: `Study, with WebFetch on real pages and repositories: Plane (makeplane/plane) board/list/calendar/gantt, Huly tracker, Trello and Jira board conventions (public docs), Linear list and filter UI (public docs), Google Calendar conventions, cal.com scheduling UI, Notion table/board views, Things 3 / Todoist task-list conventions (public pages), Luma event pages, Linear inbox, Tremor and Vercel Analytics dashboards, Notion page editor. Extract for OUR screens: board columns and cards, card detail two-column layout, table/list density and inline edit, filter chips and saved views, calendar and timeline interaction, event page anatomy with RSVP, inbox list+detail, personal task list with nesting and Pomodoro, analytics KPI tiles and chart cards, page editor with slash menu. For each: the convention, a concrete spec, adaptable open-source code with licence and exact version.` },
  { key: 'motion-and-visual-craft', prompt: `Study, with WebFetch: motion.dev docs (React: motion, AnimatePresence, layout/layoutId, useSpring, MotionConfig reducedMotion, exact current npm version of "motion"), animations.dev / Emil Kowalski's public articles (Vaul, Sonner, "Great animations" principles), Josh Comeau on springs, Rauno Freiberg's craft notes, Magic UI and Aceternity UI component sources (which are MIT and adaptable: shimmer, number ticker, animated list, dock, spotlight, border beam, blur fade, text reveal), shadcn/ui charts, @number-flow/react, react-day-picker v9, View Transitions API usage with React Router-less apps, theme-toggle circular reveal, the unDraw / Open Peeps / Humaaans illustration licences. Produce a MOTION RECIPE BOOK for React 19 + Tailwind v4: for every row in docs/03-plan/UI-OVERHAUL.md §3 give working code (a small component or hook), the reduced-motion variant, and performance notes (transform/opacity only, will-change hygiene, no layout thrash in lists over 100 items). Also: dark-mode craft (elevation via borders + tinted surfaces), shadows scale, focus rings, glass/blur usage limits, ambient gradient recipe, skeleton shimmer recipe.` },
]
let refs = []
if (run('research')) {
  phase('Research')
  refs = await parallel(research.map(r => () => agent(`${CTX}\n\nRESEARCH TASK (${r.key}): ${r.prompt}\nWrite the result as a well-structured markdown file to ${ROOT}/docs/03-plan/ui-references/${r.key}.md (create the folder; 300–700 lines; every claim with its source URL; code blocks where code is adaptable; a final "What Devon adopts" checklist). Do not edit any other file. Return status, summary and the file path in notes.`, { label: `research:${r.key}`, phase: 'Research', agentType: 'general-purpose', model: 'sonnet', effort: 'medium', schema: DONE })))
  for (let i = 0; i < research.length; i++) log(`research ${research[i].key}: ${refs[i] ? refs[i].status : 'died'} — ${refs[i] ? refs[i].summary.slice(0, 160) : ''}`)
}

// ---------- Foundation ----------
let foundation = null
if (run('build') && !(args && args.skipFoundation)) {
  phase('Foundation')
  foundation = await mk('foundation', 'Foundation', `TASK (on master in ${ROOT}, nobody else is editing the repo while you work): build the design-system and shell foundation the whole overhaul stands on. Read docs/03-plan/UI-OVERHAUL.md, DESIGN.md, docs/03-plan/ui-references/*.md, packages/ui/src, apps/web/src/shell, apps/web/src/lib, apps/web/src/routes, apps/web/src/features/home and one feature (features/work) to see how screens are composed today. Then deliver, committed on master in small commits:
1) Motion foundation: add "motion" (motion.dev, exact version) to packages/ui; packages/ui/src/motion/ exporting the tokens from DESIGN.md as JS (durations, eases, springs), a MotionProvider (MotionConfig reducedMotion="user"), and reusable pieces for EVERY row of UI-OVERHAUL.md §3: PageTransition (View Transitions when supported, AnimatePresence fallback), Stagger/StaggerItem, Reveal/BlurFade, HoverLift, PressScale, Collapsible (height auto), Shimmer skeleton, Celebrate (12-particle burst from an element), AnimatedCheck, ProgressRing, AmbientGradient, IdleFloat, useViewTransitionTheme (circular reveal), HoverCard. Each piece honours reduced motion by replacing, not removing.
2) Primitives, all in packages/ui with stories and unit tests where the neighbours have them: upgrade Button (press scale, loading morph, success morph), Dialog (scale + blur backdrop), Sheet (Vaul spring), Tooltip and Popover (fade + rise), Toast (Sonner with undo progress bar), Skeleton (shimmer); add Checkbox (with Celebrate), Switch, RadioGroup, Tabs (sliding underline via layoutId), Select/Combobox (cmdk-based, async, Cyrillic-safe search), DatePicker (react-day-picker, exact version, week starts Monday, uz/ru/en month names), Progress, ProgressRing, Chip/Tag, Breadcrumb, Card (hover lift variant), KpiTile (NumberFlow, delta arrow), EmptyState (illustration slot + one action), ErrorState, NoPermissionState, OfflineBanner polish, PageHeader (title, description, actions, tabs), SectionCard (settings), FilterChip, AvatarStack, Kbd polish, DataList/Row primitives for dense lists, and the AI affordance pair every feature will use: SparkleButton (icon button with a subtle shimmer) and AiPreviewPanel (pure UI: title, streaming-feel skeleton while pending, result slot, cost line, Accept / Edit / Discard, error state) — the data hook useRunAiFeatureMutation and FEATURE_FORMS already exist in apps/web/src/features/ai and stay there. Ship 8–12 open-licence SVG illustrations (unDraw/Open Peeps style, recoloured to tokens via currentColor/CSS vars) under packages/ui/src/illustrations with an index.
3) Shell rebuilt to the Jakob map (UI-OVERHAUL.md §2 row 1–2): Linear/Huly-style sidebar (grouped entries from the feature manifests, counts, morphing active pill, collapse to icons with tooltips, department switcher popover, bottom user block), top bar (quick-add button, search/⌘K, inbox bell with badge pop, theme toggle with circular reveal, locale switcher, avatar menu), page container widths, PageTransition on route change, route-level skeleton while lazy chunks load, shortcuts overlay on "?", command palette restyled like Raycast (sections, icons, keyboard hints, recent items), 390 px behaviour (sidebar becomes a Vaul sheet, bottom tab bar for the five most used areas). Keep every existing route, manifest contract, guard and forced-state behaviour working; nav.test.ts and the shell tests must still pass (update tests only where the DOM legitimately changed).
4) Auth and Home to the new standard: login, register, setup, join, not-found, and the Home screen (greeting by time of day, tiles with stagger, onboarding checklist card, pinned charts) — these prove the foundation on real screens.
5) DESIGN.md v2: update tokens (add elevation/surface scale for dark mode, focus ring, ambient gradient, illustration colours), replace the motion section with the full catalogue and per-component mapping, add the Jakob's Law map and "screen recipes" (page header, list, board, detail panel, settings, empty state) so wave agents can follow them without guessing. Raise the old "no animated backgrounds" rule to "ambient gradients only on auth and hub, always reduced-motion safe".
6) Prove: node agentic/scripts/gate.mjs --profile fast green, pnpm --filter @devon/web build within the bundle budget (node agentic/scripts/check-bundle.mjs), boot with pnpm start --demo and screenshot login, home, /work and /events at 1440 and 390 in both themes in the in-app browser; iterate until they look like the references. Return branch "master", the list of new primitives in notes.`, { model: 'opus', effort: 'high' })
  log(`foundation: ${foundation ? foundation.status : 'died'} — ${foundation ? foundation.summary.slice(0, 200) : ''}`)
  if (!foundation || foundation.status === 'BLOCKED') throw new Error('foundation blocked: ' + (foundation && foundation.notes))
}

// ---------- Wave ----------
const areas = [
  { key: 'shell-auth-home', paths: 'apps/web/src/shell, apps/web/src/routes, apps/web/src/lib, apps/web/src/features/accounts, apps/web/src/features/home, plus shared catalogue keys prefixed shell.*, auth.*, home.* in packages/i18n/messages/<locale>.json', prompt: `AREA shell-auth-home. Finish and perfect what the foundation started: the shell at every width (1440, 1024, 390) with the sidebar sheet and bottom tab bar on mobile, keyboard navigation through the sidebar, the command palette with real async sources (people, cards, events, pages, actions) and recent items, the shortcuts overlay, the inbox bell drawer entry animation, department switcher; auth screens (login with 2FA step and error shake, register with photo upload preview and password strength, setup, join with key + password and the pending-approval state, forgot/reset flows) with the ambient gradient and the ministry-navy touchpoint; account settings to the settings recipe (sub-nav, section cards, sessions list with device icons, 2FA enrolment with QR, danger zone); Home per role (member, head, super admin) with staggered tiles, onboarding checklist, pinned charts, empty states for a brand-new department; not-found and route error boundary screens with illustrations.` },
  { key: 'work-projects', paths: 'apps/web/src/features/work, apps/web/src/features/projects and their message files under packages/i18n/messages/modules/', prompt: `AREA work-projects. Rebuild the People board to Trello/Linear/Plane quality: sticky unit section headers with colour, columns with member header (avatar, name, load count), cards with label bar, priority glyph, due chip with risk colour, checklist fraction, comment count, giver avatar; drag with spring physics and drop settle, column highlight, keyboard DnD with live region, inline "+ Add card" at the column foot with the quick-add parser (AI sparkle for parse preview), column collapse, virtualisation kept. Card detail as the two-column recipe (routed panel over the board, full page at 390): inline-editable title, rich description, checklist with celebrations, comments with mentions and reactions-free timeline, properties sidebar with pickers (assignee, giver, dates with DatePicker, priority, labels, watchers, project), activity timeline collapsible, AI actions (subtasks, summarise thread, translate) as preview-then-accept. Table view (dense, sticky header, sort, inline edit, group by, bulk bar with undo), Calendar (Google-Calendar conventions), Timeline (bars, today line, zoom), Mine and Archive views, filter chips + saved views tabs, every empty/loading/error state, stagger on filter change. Projects: cards with progress ring and pulse, project page with objective/subjective tabs, members strip, milestones timeline, AI sprint/plan preview where it exists.` },
  { key: 'events-inbox', paths: 'apps/web/src/features/events, apps/web/src/features/inbox and their message files under packages/i18n/messages/modules/', prompt: `AREA events-inbox. Events to Luma quality: list with cover illustrations and date blocks, category colours, month grouping with stagger; calendar view; event page with big cover, date block, place with map link, RSVP segmented control with celebration on Yes, guests stepper, attendees avatar stack with count and a "who's coming" sheet, capacity meter with waitlist state, organiser update banner with diff, comments, carpool cards (driver, seats, claim with animation), polls (options bars animate, vote, results), items-to-bring checklist, .ics button, cancelled state; new-event form as a stepper with AI draft preview. Inbox to Linear quality: list + detail split (stack at 390), unread dot, reason chips with colour, j/k keyboard, mark read/archive with undo, group by reason, inline actions (approve, RSVP, open), empty state that celebrates inbox zero; preferences as the settings recipe (matrix of type × channel with Switches, quiet hours with a time-range picker, digest frequency); Telegram screen with the link code, a phone mock-up of the bot, connected state.` },
  { key: 'personal', paths: 'apps/web/src/features/personal and its message files under packages/i18n/messages/modules/', prompt: `AREA personal. The private workspace to Things/Todoist/Pomofocus quality: Today view first with the sprint header (goal, progress ring, time left), nested checkbox tasks with indent guides, drag reorder with spring, keyboard (Enter new, Tab indent, Shift-Tab outdent, Cmd-Enter done), celebrations on done, rollover banner; Sprints view with a picker (3h/day/week/custom) and history cards; Notes with a calm editor; Canvas (Excalidraw) with a sticky-note toolbar and autosave indicator; Pomodoro as a big ring with phase colours, one primary button, cycle dots, settings sheet, sounds toggle, the mini widget in the top bar that keeps running across routes (coordinate with the shell's slot; do not edit the shell — expose a component the shell already mounts or document the hook in notes); stats with KPI tiles; every empty state teaches the first step; privacy note visible once.` },
  { key: 'structure-departments', paths: 'apps/web/src/features/structure, apps/web/src/features/departments and their message files under packages/i18n/messages/modules/', prompt: `AREA structure-departments. Structure: tree list of bo'limlar with colour dots, inline rename, drag reorder with spring, nesting collapse animation, delete with undo, self-assign controls, unit roles as chips; the org chart with unit colours, vacancies dashed, zoom/pan, click-to-open side panel, works with zero heads. People directory: search-first, cards grid with avatar/title/unit chip, hover card, filters by unit, empty and no-results states. Departments hub: create-or-join as two big cards with illustrations, create request as a stepper (name, units, settings), pending state with illustration and status timeline, approval queue for the super admin with approve/reject sheets, department detail with settings sections (self-assign, structure edit, join password, invite link + copy + QR with a real QR component, regenerate with confirmation), members list with roles, department switcher entry.` },
  { key: 'analytics-pages-ai-admin', paths: 'apps/web/src/features/analytics, apps/web/src/features/pages, apps/web/src/features/ai, apps/web/src/features/admin and their message files under packages/i18n/messages/modules/', prompt: `AREA analytics-pages-ai-admin. Analytics to Vercel/Tremor quality: KPI tiles with NumberFlow and delta arrows, chart cards with owner question, draw-in, hover crosshair tooltips, filter bar with chips and date presets, saved filters as tabs, pin/unpin animation, CSV/PNG export menu, personal stats section, empty states per section. Pages to Notion quality: page tree sidebar, cover + icon, block editor with slash menu, callouts, task lists, mentions, autosave indicator, version history side panel with diff, onboarding template editor as a checklist builder. AI: settings screen (budget gauge ring, flags as Switches, usage table), and the shared preview-then-accept panel used by every feature (sparkle button, streaming-feel skeleton, Accept/Edit/Discard, cost line). Admin console to Vercel/Supabase quality: overview with health tiles and sparkline-free counters, departments table with status pills and row drawer (view-as button, pause with reason sheet), requests queue, accounts table with actions menu, global analytics, audit viewer with chain-verify badge animation, health page with live status dots, settings (registration toggle, maintenance message editor in four locales with live preview, wipe ceremony as a multi-step full dialog with the countdown ring; never execute the wipe).` },
]
const selected = (args && Array.isArray(args.areas) && args.areas.length) ? areas.filter(a => args.areas.includes(a.key)) : areas
let built = []
if (run('build')) {
  phase('Worktrees')
  const setup = await agent(`In ${ROOT} create one git worktree per area from current master. For each key in [${selected.map(a => a.key).join(', ')}]: if "${ROOT}/.claude/worktrees/ui-<key>" already exists leave it alone; else if branch ui/<key> exists run git worktree add "${ROOT}/.claude/worktrees/ui-<key>" ui/<key>; else run git worktree add "${ROOT}/.claude/worktrees/ui-<key>" -b ui/<key> master. Then run git worktree list and return {"status":"DONE","summary":"<the list>"}.`, { label: 'worktrees', phase: 'Worktrees', agentType: 'general-purpose', model: 'sonnet', effort: 'low', schema: DONE })
  log(`worktrees: ${setup ? setup.summary.slice(0, 300) : 'died'}`)

  phase('Wave')
  const CONT = (args && args.continue) ? `A PREVIOUS AGENT ALREADY WORKED ON THIS AREA in this worktree and its work is committed on your branch. Start with: git log --oneline master..HEAD && git status && git diff --stat master..HEAD; CONTINUE from there — do not redo what is done, finish what is missing, fix what is broken. ` : ''
  const results = await parallel(selected.map(a => () => mk(`ui:${a.key}`, 'Wave', `${CONT}YOUR WORKING COPY IS A GIT WORKTREE AT ${WT(a.key)} ON BRANCH ui/${a.key}. Every Bash command must start with: cd "${WT(a.key)}" && … ; use absolute paths under ${WT(a.key)} for Read/Edit/Write; NEVER read or edit files under ${ROOT}/apps or ${ROOT}/packages directly. First: cd "${WT(a.key)}" && pnpm install --prefer-offline. You may edit ONLY: ${a.paths}. Do not edit packages/ui, the shell, other features or the shared catalogues (a new shared-looking component goes into your feature's components/ folder; say so in notes so the merge promotes it). Boot your own copy on free ports (read scripts/start.mjs for the env vars; the shared Postgres from Docker is fine to reuse) and check every screen you touch in the in-app browser at 1440 and 390, light and dark, uz-Latn and ru. Commit on your branch as you go; do not merge, rebase or switch branches.\n\n${a.prompt}\n\nStandard for every screen you touch: the page header recipe, staggered lists, hover lifts, designed empty/loading/error/no-permission states with illustrations, four-locale strings, keyboard paths, reduced-motion variants, 390 px layout. AI WIRING IS PART OF YOUR AREA: the AI module shipped its features but never wired them into host screens. Wherever your prompt names an AI affordance (quick-add parse, subtasks, thread summary, translate, sprint plan, weekly summary, event draft, NL analytics) wire it for real: import useRunAiFeatureMutation and FEATURE_FORMS from apps/web/src/features/ai (import only, never edit that folder unless it is yours) and the SparkleButton + AiPreviewPanel from packages/ui; preview then Accept/Edit/Discard; it must work with the mock provider when AI_API_KEY is empty. Finish with fast gates green in your worktree.`).then(r => ({ key: a.key, r: r ? { ...r, branch: `ui/${a.key}` } : null }))))
  built = results.filter(Boolean)
  for (const { key, r } of built) log(`wave ${key}: ${r ? r.status : 'died'} — ${r ? r.summary.slice(0, 160) : ''}`)

  phase('Merge')
  const m = await mk('merge', 'Merge', `TASK: integrate the area branches into master in the main checkout ${ROOT}. Branches: ${built.map(x => `${x.key} → ui/${x.key} (worktree ${WT(x.key)})`).join('; ') || '(none reported: run git branch --list "ui/*" and git worktree list)'}. First, in each worktree, commit any uncommitted work (git add -A && git commit -m "ui: wip"). Then in the main checkout, for each branch, smallest diff first: git merge --no-ff ui/<key>; resolve conflicts keeping both sides' intent (message files: union of keys; manifests: union of entries); after each merge run pnpm install and node agentic/scripts/gate.mjs --profile fast and fix what broke before the next merge. Then promote duplicated feature-local components into packages/ui where two areas built the same thing (keep the better one, update imports), regenerate the i18n catalogues (pnpm --filter @devon/i18n run messages:merge), run the fast gates and pnpm --filter @devon/web build (bundle budget), commit "ui: merge <areas>". Remove the ui-* worktrees (git worktree remove) but keep the branches. Report branch "master".`)
  log(`merge: ${m ? m.status : 'died'} — ${m ? m.summary.slice(0, 200) : ''}`)

  phase('Integrate')
  const i = await mk('integrate', 'Integrate', `TASK: make the overhauled product run and capture it. In ${ROOT} on master: start Docker if needed, run pnpm start --demo in the background, open the app in the in-app browser, log in as each demo role and click through EVERY route (sidebar + command palette + e2e/routes.json) at 1440 and 390 in light and dark, in uz-Latn and ru. Fix every runtime error, blank screen, broken navigation, missing translation, layout break or motion glitch at the root cause; commit "ui: fix <what>". Then write a Playwright screenshot script in e2e/ (reuse e2e's fixtures and the demo login; do not weaken existing specs) that visits every route in e2e/routes.json as the demo head at 1440×900 and 390×844, light and dark (read apps/web/src/lib/theme.ts for how the theme is set), and saves PNGs to ${ROOT}/${LEDGER}/after/<route>__<width>__<theme>.png; run it; commit the script. Run node agentic/scripts/gate.mjs --profile fast, pnpm --filter @devon/web build, node agentic/scripts/check-bundle.mjs and pnpm --filter @devon/web test:a11y if it exists; fix failures. Return status, routes verified, and known issues in notes. Report branch "master".`)
  log(`integrate: ${i ? i.status : 'died'} — ${i ? i.summary.slice(0, 200) : ''}`)
}

// ---------- Polish ----------
if (run('polish')) {
  phase('Critique')
  const CRIT = { type: 'object', properties: { issues: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, impact: { type: 'string', enum: ['SEV1', 'SEV2', 'SEV3'] }, issue: { type: 'string' }, fix: { type: 'string' } }, required: ['route', 'impact', 'issue', 'fix'] } }, summary: { type: 'string' } }, required: ['issues', 'summary'] }
  const crit = await agent(`${CTX}\n\nYou are the design lead. Read docs/03-plan/UI-OVERHAUL.md and DESIGN.md, then Read every PNG under ${ROOT}/${LEDGER}/after/ (if the folder is empty, boot pnpm start --demo and walk every route yourself in the in-app browser at 1440 and 390, light and dark). Also open the live app and try the motions: route change, list stagger, board drag, card open, checkbox celebration, dialogs, toasts with undo, theme toggle, command palette, reduced motion (emulate via the browser). Critique mercilessly against the Jakob map and the motion catalogue: hierarchy, rhythm, tokens, states, copy naturalness in uz-Latn and ru, density, dark mode, 390 px, consistency, motion quality (jank, wrong duration, missing feedback, gratuitous motion). Write ${ROOT}/${LEDGER}/critique.md (ranked, with the screenshot path for each issue) and return the issues (max 40) ranked by impact with a concrete component-level fix each.${(args && args.critiqueNotes) ? ('\nNOTES FROM THE ORCHESTRATOR: ' + args.critiqueNotes) : ''}`, { label: 'critique', phase: 'Critique', agentType: 'general-purpose', model: 'opus', effort: 'high', schema: CRIT })
  const issues = (crit && crit.issues) || []
  log(`critique: ${issues.length} issues — ${crit ? crit.summary.slice(0, 200) : 'died'}`)

  phase('Fix')
  const top = issues.filter(x => x.impact !== 'SEV3').slice(0, 30)
  if (top.length) {
    const f = await mk('fix', 'Fix', `TASK on master in ${ROOT}: implement exactly these design-lead fixes (read ${LEDGER}/critique.md for context and screenshot paths):\n${top.map((t, n) => `${n + 1}. [${t.impact}] ${t.route}: ${t.issue} → ${t.fix}`).join('\n')}\nCheck each fix in the in-app browser. Commit in groups "ui: <what>". Finish with fast gates green and the bundle within budget. Report branch "master" and list any fix you could not do in notes.`)
    log(`fix: ${f ? f.status : 'died'} — ${f ? f.summary.slice(0, 200) : ''}`)
    const after = await mk('recapture', 'Fix', `TASK in ${ROOT}: re-run the Playwright screenshot script the integration step committed under e2e/ (e2e/scripts/ui-blitz-shots.mjs; boot pnpm start --demo first) with the output folder ${ROOT}/${LEDGER}/final/ — FIRST extend its route list beyond e2e/routes.json to every sidebar route (/, /inbox, /work, /work/table, /work/calendar, /work/timeline, /work/mine, /projects, /personal, /events, /people, /structure, /pages, /analytics, /ai, /departments, /account, /admin, /admin/departments, /admin/accounts, /admin/audit, /admin/health, /admin/settings as the super admin) and make the uz-Latn/ru locale switch real (verify two captures of the same route differ), commit that script change — then write ${ROOT}/${LEDGER}/report.md: per issue in critique.md say fixed / partially / not fixed with the before and after screenshot paths, plus a short plain-language summary for the CTO. Do not edit product code. Return DONE with the report path in notes.`, { effort: 'medium' })
    log(`recapture: ${after ? after.status : 'died'}`)
  }
}

return { stage: STAGE, research: refs.map(r => r && r.status), foundation: foundation && foundation.status, wave: built.map(x => ({ key: x.key, status: x.r && x.r.status })) }
