export const meta = {
  name: 'uzbek-copy',
  description: 'Rewrite every uz-Latn and uz-Cyrl string so it reads as natural Uzbek written by a native civil servant, not as a translation: two Opus writers on disjoint module sets in their own worktrees (values only, keys and code untouched), then a native-quality review on the live app that fixes what still reads awkwardly.',
  whenToUse: 'Any time; safe beside other work because only message values change. args: {ts}.',
  phases: [
    { title: 'Style guide', detail: 'packages/i18n/UZBEK-STYLE.md — register, terminology, patterns, forbidden calques' },
    { title: 'Rewrite', detail: 'two writers, disjoint modules, uz-Latn first then uz-Cyrl via transliteration + hand check' },
    { title: 'Merge + review', detail: 'merge both branches, walk the live app in both scripts, fix what still reads awkwardly' },
  ],
}
const ROOT = 'C:/Users/rpwal/Documents/Work/eGov/WorkPortal'
const WT = (k) => `${ROOT}/.claude/worktrees/uz-${k}`
const DONE = { type: 'object', properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, branch: { type: 'string' }, commits: { type: 'number' }, summary: { type: 'string' }, strings_changed: { type: 'number' }, gates_green: { type: 'boolean' }, notes: { type: 'string' } }, required: ['status', 'summary'] }
const CTX = `WorkPortal (codename Devon) is a work-tracking platform for a department of Uzbekistan's Ministry of Digital Technologies. Its default language is Uzbek (Latin, uz-Latn) with Uzbek Cyrillic (uz-Cyrl), Russian and English complete. The CTO's verdict on the current Uzbek: "it clearly seems like merely a translation — it doesn't read or sound natural, it reads awkward". Your job is to make every Uzbek string read as if a thoughtful native speaker who works in a ministry wrote it for colleagues: correct, warm, brief, and idiomatic — never a word-for-word rendering of the English or Russian.
GROUND RULES: (1) Values only: never rename, add or remove a message key, never touch code, never change ICU placeholders ({name}, {count, plural, …}), HTML-ish tags or line breaks — the i18n parity gate must stay green (node agentic/scripts/check-i18n.mjs). (2) Orthography: Latin uses the modifier letters oʻ gʻ (U+02BB) and the apostrophe ʼ (U+02BC) where the rules require; Cyrillic uses ў ғ қ ҳ correctly; no ASCII ' or backticks in user copy; the transliteration test in packages/i18n must pass. (3) Register: polite plural "siz" everywhere; imperative button labels in the infinitive-noun form the Uzbek UI convention uses (Saqlash, Bekor qilish, Yuborish), never "Siz saqlashingiz mumkin"-style descriptions on buttons; headings as nouns; error messages that say what happened and what to do; empty states that teach the next action in one friendly sentence; no exclamation marks except celebrations; numbers with a space thousands separator and a comma decimal. (4) Terminology from packages/i18n/TERMS.md is binding (boshqarma, boʻlim, xodim, boshliq, vazifa, loyiha, tadbir, muddat, …); where TERMS.md is silent, choose the word a ministry employee actually uses, prefer Uzbek roots over Russian loans where the Uzbek word is in real use (but keep loanwords everyone uses — "fayl", "havola", "sozlamalar"), and add the decision to the style guide. (5) Read the string in context: open the screen or component that uses the key (grep the key in apps/web, apps/miniapp, apps/api templates) so the phrasing fits the place — a chip, a toast, a heading, a Telegram message and a form hint are written differently. (6) uz-Cyrl is produced FROM the corrected uz-Latn with packages/i18n's transliterate helper and then hand-checked for the Cyrillic-specific spellings (ё/е, ц, ъ, loanwords), never written independently, so both scripts say the same thing. (7) Keep a change log (${'${LOG}'}) with before → after for every string you change and a one-line reason for anything non-obvious. Commit in batches per module: "uz: <module> — natural Uzbek". Return JSON matching the schema.`

// ---------- Style guide ----------
phase('Style guide')
const guide = await agent(`${CTX.replace('${LOG}', 'n/a')}\n\nTASK in ${ROOT} on master (read-only except the one file you write; another agent is fixing master, so do not run gates or touch anything else): write packages/i18n/UZBEK-STYLE.md, the binding style guide for all Uzbek copy in this product, in Uzbek (Latin) with a short English preface. Read packages/i18n/TERMS.md, DESIGN.md §5 copy rules, packages/i18n/messages/uz-Latn.json and ten module files under packages/i18n/messages/modules/*/uz-Latn.json to see the current voice and its failures. Cover: register and address; button and menu label forms; headings; toasts and undo; error and validation messages; empty, loading, no-permission and offline states; notification and Telegram message shapes (short, actionable, with the deep link last); date, time, number and duration formats; plural and counting ("3 ta vazifa", never "3 vazifalar"); word order and particles that mark translated text (list at least 25 concrete calques to avoid with the natural alternative, e.g. "muvaffaqiyatli saqlandi" → "Saqlandi", "iltimos, kuting" → "Biroz kuting", "foydalanuvchi" vs "xodim", "yaratish" vs "ochish/qoʻshish" per object, "amalga oshirildi", "mavjud emas", "ma'lumotlar" overuse, "tizim" overuse); terminology table for every domain noun and verb in TERMS.md plus the v1.1 additions (custom fields = maydonlar, workload = yuklama, goals = maqsadlar, automations = qoidalar/avtomatlashtirish, dependencies = bogʻliqliklar, estimate = baho/taxminiy vaqt, focus list = diqqat markazi, templates = andozalar, reminders = eslatmalar, person page, indicators = koʻrsatkichlar, join approval, capabilities = imkoniyatlar); the Cyrillic conventions. Commit only that file: "i18n: Uzbek style guide". Return DONE.`, { label: 'style-guide', phase: 'Style guide', agentType: 'general-purpose', model: 'opus', effort: 'high', schema: DONE })
log(`style guide: ${guide ? guide.status : 'died'}`)

// ---------- Rewrite ----------
const groups = [
  { key: 'a', modules: 'the shared catalogue packages/i18n/messages/uz-Latn.json and uz-Cyrl.json (shell, auth, common, errors, states) and the modules accounts, departments, structure, people, work, projects, fields' },
  { key: 'b', modules: 'the modules events, personal, inbox, notifications, telegram, miniapp, analytics, pages, ai, admin, automations, calendar, home, goals, workload and any other module folder under packages/i18n/messages/modules/ not in group a (list them; nothing may be left uncovered between the two groups), plus the Telegram bot templates in apps/api/src/modules/telegram/templates.ts and the API-side notification texts if they hold Uzbek literals' },
]
phase('Rewrite')
const setup = await agent(`In ${ROOT}: for each key in [a, b]: if "${ROOT}/.claude/worktrees/uz-<key>" exists leave it; else git worktree add "${ROOT}/.claude/worktrees/uz-<key>" -b uz/copy-<key> master (git branch -f first if the branch exists). No env file is needed for this work. Return {"status":"DONE","summary":"<git worktree list>"}.`, { label: 'worktrees', phase: 'Rewrite', agentType: 'general-purpose', model: 'opus', effort: 'medium', schema: DONE })
log(`worktrees: ${setup ? setup.summary.slice(0, 200) : 'died'}`)
const results = await parallel(groups.map(g => () => agent(`${CTX.replace('${LOG}', `${ROOT}/docs/03-plan/v1.1/uzbek-copy-log-${g.key}.md`)}\n\nYOUR WORKING COPY IS A GIT WORKTREE AT ${WT(g.key)} ON BRANCH uz/copy-${g.key}. Every Bash command must start with: cd "${WT(g.key)}" && … ; absolute paths under ${WT(g.key)} for Read/Edit/Write; never touch ${ROOT} itself. First: cd "${WT(g.key)}" && pnpm install --prefer-offline, then git merge --ff-only master is NOT needed (you branched from it) — but read packages/i18n/UZBEK-STYLE.md from ${ROOT} (committed on master after you branched: run git -C "${WT(g.key)}" merge master first so you have it).\n\nTASK: rewrite EVERY uz-Latn string in ${g.modules}, then regenerate uz-Cyrl for the same files from your corrected uz-Latn (transliterate helper, then hand-check the Cyrillic-specific spellings). Method, per module: (1) list every key; (2) for each key open the place it is used (grep the key in apps/web/src, apps/miniapp/src, apps/api/src) so you know whether it is a heading, button, chip, tooltip, toast, form hint, error, empty state, notification or Telegram text; (3) rewrite the value so a native ministry employee would find it natural — do not keep a string just because it is grammatically correct; if it sounds translated, rewrite it; (4) keep placeholders and plural syntax byte-identical; (5) run node agentic/scripts/check-i18n.mjs and pnpm --filter @devon/i18n test:unit after each module; (6) commit per module. Expect to change the majority of strings. Return strings_changed and the log path. Report branch "uz/copy-${g.key}".`, { label: `uz:${g.key}`, phase: 'Rewrite', agentType: 'general-purpose', model: 'opus', effort: 'high', schema: DONE })))
for (let i = 0; i < groups.length; i++) log(`group ${groups[i].key}: ${results[i] ? results[i].status : 'died'} — ${results[i] ? (results[i].strings_changed || 0) + ' strings' : ''}`)

// ---------- Merge + review ----------
phase('Merge + review')
const review = await agent(`${CTX.replace('${LOG}', `${ROOT}/docs/03-plan/v1.1/uzbek-copy-log-review.md`)}\n\nTASK: merge and review. (1) In ${ROOT}: git worktree add "${ROOT}/.claude/worktrees/uz-review" -b uz/copy-review master, then in that worktree git merge --no-ff uz/copy-a and uz/copy-b (conflicts only if master changed the same string meanwhile: keep master's KEY set and the writers' VALUES; for a string master added after the branch point, rewrite it yourself to the style guide). Run node agentic/scripts/check-i18n.mjs, pnpm --filter @devon/i18n test:unit, the fast gate. (2) Review on the live app: boot the app in this worktree on free ports (read scripts/start.mjs; build DATABASE_URL and MIGRATION_DATABASE_URL from infra/docker-compose.yml's defaults for the running devon-postgres on 55432 with your own database name, e.g. devon_uzreview; demo logins in MODULE-GUIDE.md), then walk EVERY screen as demo.xodim and demo.boshliq (and /admin as admin.super) in uz-Latn and again in uz-Cyrl with the chrome-devtools MCP, reading every visible string as a demanding native speaker: fix on the spot anything that still reads awkward, inconsistent with the style guide or the terminology, wrongly cased, truncated at 390 px because Uzbek is longer, or mis-transliterated; also open the Telegram templates and Mini App strings. Write ${ROOT}/docs/03-plan/v1.1/UZBEK-COPY-REVIEW.md: what changed overall (counts per module), the twenty worst before → after examples, remaining doubts. Commit on uz/copy-review. Do NOT merge into master yourself (another agent is fixing master); report branch "uz/copy-review" and the exact merge command for the orchestrator.`, { label: 'uz:review', phase: 'Merge + review', agentType: 'general-purpose', model: 'opus', effort: 'high', schema: DONE })
log(`review: ${review ? review.status : 'died'} — ${review ? review.summary.slice(0, 200) : ''}`)
return { guide: guide && guide.status, groups: results.map((r, i) => ({ key: groups[i].key, status: r && r.status, strings: r && r.strings_changed })), review: review && review.status }
