export const meta = {
  name: 'v11-blitz',
  description: 'v1.1: roles done right (head console vs member workspace), person pages, the people table with dynamic and custom columns, ClickUp-grade work features, AI features rebuilt with purpose, the remaining phase-2 epics, then browser-driven testing, critique and fix — Opus builders, Fable adjudication.',
  whenToUse: 'After docs/03-plan/v1.1/SPEC.md exists. args: {ts, stage: "skeleton"|"build"|"verify"|"all", skipSkeleton, continue, packages: [keys]}.',
  phases: [
    { title: 'Skeleton', detail: 'permission matrix enforced server-side, role-aware shell, shared people-indicators service, department switcher — on master' },
    { title: 'Skeleton 2', detail: 'notification pipeline repair, join approval, head password reset, board defaults, feature switches, walkthrough basics, seed scrub — on master' },
    { title: 'Worktrees', detail: 'one worktree per package on v11/<key>' },
    { title: 'Wave', detail: 'head-console, custom-fields, work-plus, ai-refit, telegram-miniapp, realtime-calendar — in parallel' },
    { title: 'Merge', detail: 'merge v11/* branches, fast gates, migrate:verify, build' },
    { title: 'Integrate', detail: 'boot, walk every flow as member/head/super admin with chrome-devtools + playwright, fix' },
    { title: 'Critique', detail: 'design lead (Opus) on the live app; Fable adjudicates the ranked list' },
    { title: 'Fix', detail: 'ranked fixes, re-verify, report' },
  ],
}

const TS = (args && args.ts) || 'unstamped'
const STAGE = (args && args.stage) || 'all'
const ROOT = 'C:/Users/rpwal/Documents/Work/eGov/WorkPortal'
const LEDGER = `agentic/ledger/v11/${TS.replace(/[:+]/g, '-')}`
const WT = (key) => `${ROOT}/.claude/worktrees/v11-${key}`
const run = (s) => STAGE === 'all' || STAGE === s

const CTX = `You are building v1.1 of Devon (WorkPortal), a self-hosted department work-tracking platform for a ministry department in Uzbekistan. Roles are exactly super_admin, head (boshqarma boshlig'i) and member (xodim). BINDING, read in this order: CLAUDE.md (tooling: use the LSP tool for TypeScript symbols instead of grep; chrome-devtools and playwright MCPs for browser work; the frontend-design skill for craft), docs/03-plan/v1.1/BRIEF.md (what the CTO found and asked for), docs/03-plan/v1.1/SPEC.md (the v1.1 design — your task names its sections), docs/03-plan/v1.1/PERMISSIONS-AUDIT.md, docs/03-plan/v1.1/AI-AUDIT.md, docs/03-plan/v1.1/CLICKUP-RESEARCH.md, docs/03-plan/v1.1/WALKTHROUGH-FINDINGS.md (fix every finding inside your paths), docs/03-plan/v1.1/STATE.md (the codebase map), MODULE-GUIDE.md (conventions, demo logins), DESIGN.md (tokens, motion catalogue, Jakob map, screen recipes), docs/03-plan/TECH-SPEC.md, agentic/INVARIANTS.md.
RULES: fully built, never a stub or a placeholder; every string in all four locales (uz-Latn, uz-Cyrl, ru, en) in your module's message files with natural Uzbek (oʻ/gʻ modifier letters); every screen has designed empty/loading/error/no-permission states; tokens only; the motion catalogue applies (stagger, hover lift, celebrations, skeletons); keyboard reachable; 390 px works; server enforces every permission with can() and RLS, the client only hides; every write audits and emits domain events; Zod on every route; no query in a loop; timeouts on outbound calls; pin exact versions. Verify in the browser as the persona that matters (member and head; super admin where relevant) using the chrome-devtools MCP or the in-app browser — screenshots of what you built go under ${ROOT}/${LEDGER}/<your-key>/ . Commit early and often: "<key>: <what a user can now do>". Before finishing: node agentic/scripts/gate.mjs --profile fast green (nothing skipped), pnpm --filter @devon/db migrate:verify if you touched packages/db, pnpm --filter @devon/web build. Return JSON matching the schema.`

const DONE = { type: 'object', properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, branch: { type: 'string' }, commits: { type: 'number' }, summary: { type: 'string' }, routes: { type: 'array', items: { type: 'string' } }, gates_green: { type: 'boolean' }, notes: { type: 'string' } }, required: ['status', 'summary'] }
const mk = (label, phase, prompt, extra) => agent(`${CTX}\n\n${prompt}`, { label, phase, agentType: 'general-purpose', model: 'opus', effort: 'high', schema: DONE, ...(extra || {}) })

// ---------- Skeleton ----------
let skeleton = null
if (run('skeleton') && !(args && args.skipSkeleton)) {
  phase('Skeleton')
  skeleton = await mk('skeleton', 'Skeleton', `TASK on master in ${ROOT} (nobody else edits while you work): implement SPEC.md §2 "Roles and the permission matrix" and §3 "Two products in one shell" so that six agents can build features in parallel on top of it.
1) packages/contracts/src/permissions.ts: the final matrix from SPEC §2 (every action, member/head/super_admin, own-only rules) with exhaustive unit tests; a typed list of actions per feature area.
2) Server: every apps/api route calls can() with the right action (use the LSP tool to enumerate routes and current calls; fix every route the PERMISSIONS-AUDIT marked as missing/weaker); head-only reads never leak to members (cross-role tests: member requesting head-only data gets 403, and list endpoints omit head-only fields); RLS unchanged unless the audit demands a policy fix (new migration only).
3) Client: a useCan(action, object?) hook and a <Can> gate in apps/web/src/lib backed by /me (role + memberships); the shell's sidebar, palette entries, page-header actions and feature manifests declare the actions they need and are hidden when the viewer cannot; the head sees the "Boshqaruv" (management) group in the sidebar (People table, Workload, Analytics for everyone, Settings, Custom fields), the member sees the working set; every existing screen fixed to hide what the matrix denies (tabs, buttons, menus, settings sections).
4) Role-aware Home: SPEC §3 — head Home is a management dashboard shell (tiles for people at risk, overdue by person, decisions needed, load this week, upcoming events, onboarding in progress, pinned charts) with real data from existing endpoints where they exist and typed placeholders where the head-console package will fill in; member Home stays the working view (due from me, needs my decision, around me, sprint, focus).
5) Shared people-indicators service (SPEC §4.2): apps/api/src/modules/people (or inside structure) exposes GET /people/indicators?ids=…&keys=… returning the registry of auto indicators per user (open cards, overdue, workload score, on-time rate, projects, events RSVP rate, last active, focus minutes, unit, unit role, joined at, onboarding progress) computed with batched queries (no N+1), cached per department for 60 s, head-only; a typed registry in packages/contracts listing every indicator with id, label key, type, format and description so the table, the person page and the head dashboard share it.
6) MODULE-GUIDE.md: a short "v1.1 conventions" section (useCan, indicators registry, custom fields model from SPEC §5 as an interface the custom-fields package implements).
7) Three documented bugs in apps/api/test/integration are yours (they are it.fails probes — make them pass by fixing the product, never the test): a member can still patch/delete a structure unit after self-service is disabled; a card can be assigned to a user outside the department; a fresh department's head cannot lazily initialise AI settings because the RLS policy rejects the insert (fix the policy in a new migration).
8) SPEC §2.3 department switcher: POST /me/active-department sets a signed cookie, actor.departmentId resolves from it per request, the client switcher calls it and invalidates queries.
Prove: gates green, migrate:verify, build, and a browser check as demo.xodim (no management items visible, 403 on head endpoints) and demo.boshliq (management group visible). Report branch "master".`)
  log(`skeleton: ${skeleton ? skeleton.status : 'died'} — ${skeleton ? skeleton.summary.slice(0, 200) : ''}`)
  if (!skeleton || skeleton.status === 'BLOCKED') throw new Error('skeleton blocked: ' + (skeleton && skeleton.notes))

  phase('Skeleton 2')
  const s2 = await mk('skeleton2', 'Skeleton 2', `TASK on master in ${ROOT} (nobody else edits while you work; a first skeleton agent already landed the permission model, useCan, the role-aware sidebar and Home, the indicators service and the department switcher — read git log --oneline -30 first): implement SPEC.md §11, §12 and the parts of §2.2 that are flows, so the six wave packages can rely on them.
1) §11 Notification pipeline repair: STATE.md §7.1 shows the outbox → inbox path produces nothing. Build one registry keyed on the events the API actually emits (enumerate them with the LSP tool), each entry mapping to a reason, a recipients rule (assignee, giver, watchers, mentioned, organizer, head, whole department), a deep link, and Telegram text builders in four locales; deliver by channel per user preferences and quiet hours; individual Telegram messages through the existing bot adapter; a unit test that fails when an emitted event name has no registry entry or a registry entry names an event nothing emits; prove it live: assign a card → the assignee's inbox shows it; mention → notification; RSVP → organizer notified. Fix the personal and department digest jobs to use the registry's builders.
2) Join approval: endpoints to list/approve/reject pending memberships (head), the Members tab UI with approve/reject and undo, inbox + Telegram notification to the head on a new request and to the joiner on the decision; default join_requires_approval = true for NEW departments (migration changes the default only), demo department keeps it off; the join screen shows the pending state.
3) Password reset by the head: POST /departments/:id/members/:userId/reset-password (temporary password, forced change, audited, member notified in-app and via Telegram); a one-click "Parolni tiklashni soʻrash" on the login screen that creates an inbox item for the head (by username, uniform response, rate limited); copy updated in four locales.
4) §3.3 board defaults: whole department grouped by bo'lim for everyone; "Hammasi | Mening" segmented control persisted per user; head default sorted by overdue then load; collapse-all, compact density; assignee as the main avatar with the giver secondary.
5) §7 Imkoniyatlar scaffold: department_settings.features jsonb with the switch keys (custom_fields, person_fields, estimates, workload, dependencies, recurring, templates, goals, focus_list, automations, reminders), a head-only settings section listing them with one-sentence descriptions (members read-only), a useFeature(key) hook and a server helper; defaults off for new departments, all on for the demo seed.
6) §12: global "+ Yangi → Yangi vazifa" opens the composer; Ctrl+K searches cards, projects, pages, events, people and actions with sections and recent items; /department without id opens the user's own; the event sheet never clips at 1440×900 and has no horizontal scroll at 390; every toLocale*() call receives the app locale; the three on-time percentages reconciled with labelled denominators; undo toasts on reassign/archive/delete for card, page, project, unit; the page editor's delete moves to the overflow menu; login defaults to uz-Latn and light; product name "WorkPortal" in all user-facing copy.
7) Demo seed scrub (§12): remove test cards/pages/triplicates/blitz departments and accounts, fix -- and ASCII apostrophes, keep the three demo logins; seed:reset + seed:demo idempotent (test:seed-idempotence green).
8) Three documented races in apps/api/test/integration are yours (it.fails probes — fix the product, never the test): the RSVP capacity race, the carpool seat race, and the card version check-then-act; make them atomic (single UPDATE … WHERE with the guard, or advisory locks) so parallel requests cannot oversubscribe.
Prove each item in the browser as demo.xodim and demo.boshliq. Gates green, migrate:verify, build. Report branch "master".`)
  log(`skeleton 2: ${s2 ? s2.status : 'died'} — ${s2 ? s2.summary.slice(0, 200) : ''}`)
  if (!s2 || s2.status === 'BLOCKED') throw new Error('skeleton 2 blocked: ' + (s2 && s2.notes))
}

// ---------- Wave ----------
const packages = [
  { key: 'head-console', paths: 'apps/api/src/modules/people (or structure/people), apps/api/src/modules/analytics only for new head aggregates, apps/web/src/features/structure (people table, person page), apps/web/src/features/home (head dashboard), packages/contracts (people views types), packages/db (new migrations for people_views), message files of those modules', prompt: `PACKAGE head-console — SPEC §4 (people table with dynamic columns, saved views, assign from row), §6 (person page), §3.2 (head dashboard). Deliver: the Xodimlar page as a real table for the head (TanStack Table + Virtual; sticky header; default columns Name, Bo'lim, Tasks (auto-listed open cards with chips and a "+N"), Workload; a column picker fed by the indicators registry plus custom fields; per-column sort/filter; group by bo'lim; density; saved views per head with a default; CSV export; row click → person page; row actions: assign a task (quick-add sheet with assignee preset, due, priority), open board column, message via Telegram deep link if linked); members see the directory (cards or a simplified table without head-only columns) per the matrix. The person page /people/:id (head; members only their own /me profile): header with avatar, name, title, bo'lim, unit role, joined, last active, Telegram linked; tabs: Overview (KPI tiles with NumberFlow: open, overdue, on-time rate, workload, focus minutes; charts: throughput per week, on-time trend, load by project; risk list), Tasks (their cards with filters), Projects (with roles and progress), Events (RSVPs, carpool, polls), Onboarding (checklist progress), Custom fields (values, missing ones highlighted, "ask to fill" button), Activity (timeline). Head dashboard Home: fill the tiles from the skeleton with real data and drill-downs (people at risk → person page; overdue by person → table view filtered; decisions needed → cards; load this week → workload view; onboarding in progress → person pages). Everything four locales, both themes, 390 px (table collapses to cards), motion catalogue.` },
  { key: 'custom-fields', paths: 'apps/api/src/modules/fields (new), apps/api/src/modules/notifications and telegram only to add the field_request reason and the individual bot message, apps/web/src/features/fields (new: head field manager, member fill UI), apps/web/src/features/accounts only for the profile "my fields" section, packages/contracts (fields types), packages/db (migrations 1000_fields), message files of those modules', prompt: `PACKAGE custom-fields — SPEC §5. Deliver custom fields for people and for cards: a field definition model (department-scoped, entity people|card, key, label in the head's locale with optional translations, type text|number|date|select|multiselect|person|url|checkbox, required, visibility member-visible|head-only, order, archived); values tables with RLS; head field manager UI (create/edit/reorder/archive with undo, choose visibility); "Notify to fill" action: creates a field_request per member, sends an in-app notification (new reason field_request with a deep link to their profile fields section) and an individual Telegram bot message (never a group) in the member's locale with an inline button, tracks who filled (progress bar in the manager, reminders after N days configurable); member profile section "Mening maʼlumotlarim" to fill values with validation; card custom fields shown in the card detail properties sidebar and editable; fields appear as columns in the people table and as filters in the work filter grammar (field:key=value) via the contracts registry the skeleton defined; audit and domain events on every write; demo seed with two people fields (education, languages) and one card field (estimate hours). Four locales, motion, states.` },
  { key: 'work-plus', paths: 'apps/api/src/modules/work, apps/api/src/modules/projects, apps/api/src/modules/automations (new), apps/web/src/features/work, apps/web/src/features/projects, apps/web/src/features/automations (new), packages/contracts (work types), packages/db (migrations 0310+ work, 1100_automations), message files of those modules', prompt: `PACKAGE work-plus — SPEC §7 (ClickUp adoptions) and EPIC-017. Deliver on cards and projects: dependencies (blocks / blocked by, with a cycle guard, shown on the card, in the Gantt as arrows and as a "blocked" chip on the board), time estimates and a light time log (estimate hours, logged minutes, remaining; per-card and summed per person for workload), recurring cards (daily/weekly/monthly/custom rule; next instance created by a job; shown as a chip), card templates and project templates gallery (department templates the head curates plus personal templates; create from template in quick-add and the project stepper), multitask toolbar (select cards on the board/table → assign, label, priority, due, move, archive with undo), Workload view (a week grid: rows per person, cells = estimated hours vs capacity per week from the person's settings, colour by load; drag a card to another person/week; head-only, members see their own row), Me mode (a toggle that filters every work view to my cards) and LineUp (pin up to 5 priority cards to the top of My tasks and Home), reminders on a card (me at time X → inbox + Telegram), goals for the department (a goal with targets tied to filters, progress auto-computed, shown on the head dashboard; EPIC-017 automations: when card created/moved/overdue/due-soon/assigned → assign, label, notify, move, create checklist; rule builder UI for the head with a log of runs). Also fix every WALKTHROUGH finding inside work and projects. Four locales, motion, states.` },
  { key: 'ai-refit', paths: 'packages/ai, apps/api/src/modules/ai, apps/web/src/features/ai, plus the exact call sites in other features named by AI-AUDIT.md (edit only the AI affordance code there), packages/db (migrations 0810+ for embeddings if used), message files of those modules', prompt: `PACKAGE ai-refit — SPEC §8 and AI-AUDIT.md. Rebuild every AI feature so it has a purpose a member or head recognises: one unique prompt specification per feature (system role, fetched inputs in a stated shape, instructions, constraints: answer in the user's locale with correct Uzbek Latin, never invent people or dates, cite card ids; JSON schema output validated with Zod; few-shot examples), the golden set extended with real cases per feature, and the UI at each host screen showing a genuinely useful preview (structured, not a wall of text: parsed fields with confidence, an ordered plan with reasons, a Monday briefing with risks and overloaded people, decisions and open questions, a complete event draft, an analytics answer with the filter it used and the numbers). Drop or merge features the audit found pointless; add the ones it recommends (explain this risk, suggest an assignee, what changed since Friday, draft a reply). AI L2 (EPIC-016): check whether the GLM endpoint offers an embeddings model (probe /v1/models and /v1/embeddings with the configured key at runtime; document the result); if yes implement pgvector embeddings for cards, comments, pages and events with a sidecar job, semantic search in the command palette and an "Ask" box that answers with citations (card/page ids as links); if no, implement the same UX on Postgres FTS with trigram fallback and say so in the UI settings. Gateway: reasoning_content never shown, retries, budget, traces, a fake-streaming skeleton; the AI settings screen explains each feature in plain words with an example. Mock provider must produce realistic structured output for every feature so the demo works without a key.` },
  { key: 'telegram-miniapp', paths: 'apps/api/src/modules/telegram (miniapp auth route, initData verification), apps/miniapp (new Vite app) or apps/web/src/miniapp (decide and document), packages/contracts (miniapp types), message files', prompt: `PACKAGE telegram-miniapp — EPIC-015, SPEC §9. Deliver a Telegram Mini App: initData HMAC verification (bot token) issuing a short-lived session bound to the linked user; screens sized for the Telegram webview using Telegram's theme params: Inbox (list, mark read, act on inline actions), Board peek (my column and the team summary), Card quick view with done/comment, Events (RSVP yes/no/maybe, carpool claim), Polls (vote), Pomodoro companion (start/stop a focus session synced with the personal workspace, notifications via the bot), Personal today list with checkboxes. Bot commands open the Mini App via a web_app button; the department settings show the bot username and a setup checklist for the head. Build it so it runs locally in a normal browser with a dev-mode initData stub (documented) and is verified end to end against a real bot when TELEGRAM_BOT_TOKEN is set. Four locales, motion, states.` },
  { key: 'realtime-calendar', paths: 'apps/api/src/modules/realtime (new) and calendar (new), apps/web/src/lib/realtime (new), the minimal presence/typing/cursor hooks inside features/work (board), features/personal (canvas), features/events (calendar feed link), infra/docker-compose.yml only for Centrifugo config, message files', prompt: `PACKAGE realtime-calendar — EPIC-018 and EPIC-019, SPEC §10. Realtime via Centrifugo (already in compose): connection token endpoint, per-department channels with RLS-equivalent authorisation, presence on the board (avatars of who is viewing, "editing" indicator on a card), typing indicators in comments, live cursors and sticky-note sync on the personal canvas only when the owner shares a canvas to an event or project (decide and document the sharing rule; the private canvas stays private), live updates of card moves and inbox counts (replace polling). Calendar: per-user secret ICS feed URLs for events and card due dates (regenerate/revoke), a CalDAV-lite read-only endpoint if feasible in time, else document; web push (VAPID) for reminders and mentions with per-user opt-in in inbox preferences and a service worker; Google/Outlook "add to calendar" links on events. Four locales, motion, states.` },
]
const selected = (args && Array.isArray(args.packages) && args.packages.length) ? packages.filter(p => args.packages.includes(p.key)) : packages
let built = []
if (run('build')) {
  phase('Worktrees')
  const setup = await agent(`In ${ROOT}: for each key in [${selected.map(p => p.key).join(', ')}]: if "${ROOT}/.claude/worktrees/v11-<key>" exists leave it; else if branch v11/<key> exists run git branch -f v11/<key> master then git worktree add "${ROOT}/.claude/worktrees/v11-<key>" v11/<key>; else git worktree add "${ROOT}/.claude/worktrees/v11-<key>" -b v11/<key> master. Copy the local env file into each new worktree so the demo can boot there: cp "${ROOT}/.env" "${ROOT}/.claude/worktrees/v11-<key>/.env" (gitignored; never print its contents). Return {"status":"DONE","summary":"<git worktree list>"}.`, { label: 'worktrees', phase: 'Worktrees', agentType: 'general-purpose', model: 'opus', effort: 'medium', schema: DONE })
  log(`worktrees: ${setup ? setup.summary.slice(0, 300) : 'died'}`)

  phase('Wave')
  const CONT = (args && args.continue) ? `A PREVIOUS AGENT ALREADY WORKED ON THIS PACKAGE in this worktree; its work is committed on your branch. Start with git log --oneline master..HEAD && git status && git diff --stat master..HEAD; CONTINUE — do not redo what is done, finish what is missing, fix what is broken. ` : ''
  const results = await parallel(selected.map(p => () => mk(`v11:${p.key}`, 'Wave', `${CONT}YOUR WORKING COPY IS A GIT WORKTREE AT ${WT(p.key)} ON BRANCH v11/${p.key}. Every Bash command must start with: cd "${WT(p.key)}" && … ; use absolute paths under ${WT(p.key)} for Read/Edit/Write; NEVER read or edit files under ${ROOT}/apps, ${ROOT}/packages or ${ROOT}/e2e directly. First: cd "${WT(p.key)}" && pnpm install --prefer-offline. You may edit ONLY: ${p.paths}. If you need a shared primitive, build it inside your feature's components/ folder and say so in notes (the merge promotes it). Boot your own copy on free ports (read scripts/start.mjs for the env vars; the shared Docker Postgres is fine — use your own database name via DATABASE_URL/MIGRATION_DATABASE_URL if your migrations could disturb others). Commit on your branch as you go; do not merge, rebase or switch branches.\n\n${p.prompt}\n\nFinish with fast gates green in your worktree, migrate:verify if you touched packages/db, build green, screenshots saved, and the result listing routes.`).then(r => ({ key: p.key, r: r ? { ...r, branch: `v11/${p.key}` } : null }))))
  built = results.filter(Boolean)
  for (const { key, r } of built) log(`wave ${key}: ${r ? r.status : 'died'} — ${r ? r.summary.slice(0, 160) : ''}`)

  phase('Merge')
  const m = await mk('merge', 'Merge', `TASK: integrate the v1.1 package branches into master in ${ROOT}: ${built.map(x => `${x.key} → v11/${x.key} (worktree ${WT(x.key)})`).join('; ') || '(run git branch --list "v11/*" and git worktree list)'}. In each worktree commit any uncommitted work first. Merge smallest diff first with git merge --no-ff; resolve conflicts keeping both intents (message files: union; manifests: union; migrations: renumber to keep order unique then migrate:verify; the indicators/fields registries: union). After each merge: pnpm install, node agentic/scripts/gate.mjs --profile fast, fix what broke at the root cause. Promote duplicated feature-local components into packages/ui. Regenerate i18n catalogues. Finish with fast gates green (nothing skipped), migrate:verify, pnpm --filter @devon/web build within the bundle budget, commit "v1.1: merge <packages>". Remove the v11-* worktrees, keep the branches. Report branch "master".`)
  log(`merge: ${m ? m.status : 'died'} — ${m ? m.summary.slice(0, 200) : ''}`)
}

// ---------- Verify ----------
if (run('verify')) {
  phase('Integrate')
  const i = await mk('integrate', 'Integrate', `TASK in ${ROOT} on master: make v1.1 run as one product and prove it in the browser. Boot pnpm start --demo (Docker up). Using the chrome-devtools MCP (navigate_page, take_snapshot, click, fill, take_screenshot, list_console_messages, list_network_requests) and the playwright MCP for repeatable sequences, walk EVERY flow as demo.xodim, demo.boshliq and admin.super at 1440 and 390, uz-Latn and ru: the permission matrix (members must not see or reach head-only things — try the URLs and the API directly), head dashboard and drill-downs, people table (columns, views, assign from row), person page, custom fields end to end (create → notify to fill → member fills → table shows), dependencies/estimates/recurring/templates/multitask/workload/Me mode/LineUp/reminders/goals/automations, every AI feature with the mock provider, the Mini App in dev mode, realtime presence with two sessions, ICS feed and push opt-in, plus the whole v1.0 surface (board, card, projects, events, inbox, personal, analytics, pages, admin). Fix every runtime error, blank screen, broken navigation, missing translation, layout break or motion glitch at the root cause; commit "v1.1: fix <what>". Extend e2e/scripts/ui-blitz-shots.mjs and e2e/routes.json with the new routes and run it into ${ROOT}/${LEDGER}/after/. Finish with fast gates green, build, migrate:verify, and pnpm --filter @devon/web test:e2e -- --grep @smoke green. Report routes verified and known issues.`)
  log(`integrate: ${i ? i.status : 'died'} — ${i ? i.summary.slice(0, 200) : ''}`)

  phase('Critique')
  const CRIT = { type: 'object', properties: { issues: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, persona: { type: 'string' }, impact: { type: 'string', enum: ['SEV1', 'SEV2', 'SEV3'] }, issue: { type: 'string' }, fix: { type: 'string' } }, required: ['route', 'impact', 'issue', 'fix'] } }, summary: { type: 'string' } }, required: ['issues', 'summary'] }
  const crit = await agent(`${CTX}\n\nYou are the design lead and a demanding department head at once. Read BRIEF.md, SPEC.md and WALKTHROUGH-FINDINGS.md, then use the live app (pnpm start --demo is probably running; else boot it) with the chrome-devtools MCP as demo.xodim, demo.boshliq and admin.super at 1440 and 390, both themes, uz-Latn and ru. Judge: does the head's product feel like management and the member's like work? Is anything head-only still visible to members? Is every new feature complete, obvious and pleasant (people table, person page, custom fields with notify-to-fill, workload, dependencies, templates, automations, goals, AI previews, Mini App, presence)? Is the copy natural Uzbek? Motion density per screen 0–5. Write ${ROOT}/${LEDGER}/critique.md (ranked, with screenshot paths under ${ROOT}/${LEDGER}/critique-shots/) and return up to 40 issues ranked with a concrete fix each.`, { label: 'critique', phase: 'Critique', agentType: 'general-purpose', model: 'opus', effort: 'high', schema: CRIT })
  const issues = (crit && crit.issues) || []
  log(`critique: ${issues.length} issues — ${crit ? crit.summary.slice(0, 200) : 'died'}`)
  const ADJ = { type: 'object', properties: { keep: { type: 'array', items: { type: 'number' } }, drop: { type: 'array', items: { type: 'number' } }, rationale: { type: 'string' } }, required: ['keep', 'rationale'] }
  const adj = await agent(`You adjudicate for the CTO of Devon (WorkPortal). Read docs/03-plan/v1.1/BRIEF.md and ${LEDGER}/critique.md. Here are the design lead's ranked issues (index: impact route/persona — issue → fix):\n${issues.map((t, n) => `${n}: [${t.impact}] ${t.route}/${t.persona || '-'} — ${t.issue} → ${t.fix}`).join('\n')}\nDecide which to fix now (keep) and which to defer (drop) for a product that must ship complete, easy and appealing: keep every SEV1 and SEV2 unless the fix contradicts BRIEF.md or the permission matrix; drop only true taste-nitpicks or items that would need a schema change with no user-visible payoff. Return keep/drop index lists and a two-paragraph rationale.`, { label: 'adjudicate', phase: 'Critique', agentType: 'general-purpose', model: 'fable', effort: 'high', schema: ADJ })
  const keep = (adj && adj.keep) || issues.map((_, n) => n)
  const top = keep.map(n => issues[n]).filter(Boolean).slice(0, 40)

  phase('Fix')
  if (top.length) {
    const f = await mk('fix', 'Fix', `TASK on master in ${ROOT}: implement exactly these adjudicated fixes (context and screenshots in ${LEDGER}/critique.md):\n${top.map((t, n) => `${n + 1}. [${t.impact}] ${t.route} (${t.persona || '-'}): ${t.issue} → ${t.fix}`).join('\n')}\nVerify each in the browser as the right persona. Commit in groups "v1.1: <what>". Fast gates green, build within budget. Report anything not done in notes.`)
    log(`fix: ${f ? f.status : 'died'} — ${f ? f.summary.slice(0, 200) : ''}`)
    const after = await mk('recapture', 'Fix', `TASK in ${ROOT}: boot pnpm start --demo, re-run e2e/scripts/ui-blitz-shots.mjs into ${ROOT}/${LEDGER}/final/, re-verify every kept issue live as the right persona, and write ${ROOT}/${LEDGER}/report.md: per issue fixed / partially / not fixed with screenshot paths, the motion scores, any regression, and a plain-language summary for the CTO. Do not edit product code.`, { effort: 'medium' })
    log(`recapture: ${after ? after.status : 'died'}`)
  }
}

return { stage: STAGE, skeleton: skeleton && skeleton.status, wave: built.map(x => ({ key: x.key, status: x.r && x.r.status })) }
