-- EPIC-018 / EPIC-019 (v1.1 SPEC §10): realtime collaboration, calendar feeds and web push.
-- Expand-only (I-15). Idempotent: `create table if not exists`, `create index if not exists`,
-- `do $$ ... exception when duplicate_object` for enum types, `drop policy if exists` + `create
-- policy` for policies.
--
-- Migration number: the 18xx block belongs to EPIC-018/EPIC-019, the phase-2 epics added after the
-- 09xx admin block MODULE-GUIDE.md's table stops at. Nothing below touches an applied migration.
--
-- No column here matches birth/dob/passport/pinfl/inn/address/salary/nationality/religio (I-2), and
-- nothing here can carry personal-workspace *content* to anyone but its owner: a shared canvas is an
-- explicit, revocable COPY the owner publishes into the department (see the comment on the table),
-- never a window onto `app.personal_canvases`, whose owner-only policy is untouched by this file.
set role devon_migrator;

-- --------------------------------------------------------------------------------------------------
-- 1. Shared canvases (SPEC §10 "canvas live cursors only for a canvas the owner shares to a project
--    or event; the private canvas stays private").
--
-- The sharing rule, decided here and documented in `docs/ops/REALTIME-CALENDAR.md`:
--   * `app.personal_canvases` stays owner-only, for ever (I-1). No policy on it is changed.
--   * The owner may publish a *copy* of one canvas to exactly one project or one event they belong
--     to. The copy is a department-owned row: it is the thing colleagues see, and it exists only for
--     as long as the share does.
--   * Participants of that project/event may open the copy; they may also edit it and move their
--     cursor on it when `allow_edit` is true. The owner may revoke at any moment, which stops the
--     live channel and hides the copy; the private original is never touched by any of it.
-- Participant narrowing (is this person a member of that project / an RSVP of that event) is decided
-- by the API handler through `can()`, exactly as card ownership is (`work/index.ts`'s
-- `requireCardOwnership`): RLS below draws the department boundary, which is the boundary a policy
-- can express without a sub-select.
do $$ begin
  create type app.shared_canvas_scope as enum ('project', 'event');
exception when duplicate_object then null;
end $$;

create table if not exists app.shared_canvases (
  id uuid primary key default gen_random_uuid(),
  department_id uuid not null references app.departments (id),
  source_canvas_id uuid not null,
  owner_user_id uuid not null references app.users (id),
  scope app.shared_canvas_scope not null,
  target_id uuid not null,
  title text not null,
  scene jsonb not null default '{"elements": [], "appState": {}}',
  stickies jsonb not null default '[]',
  allow_edit boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by_user_id uuid references app.users (id),
  revoked_at timestamptz,
  version integer not null default 1
);

create index if not exists shared_canvases_department_target_idx
  on app.shared_canvases (department_id, scope, target_id) where revoked_at is null;
create index if not exists shared_canvases_owner_idx
  on app.shared_canvases (owner_user_id) where revoked_at is null;
-- One live share per (canvas, scope, target): re-sharing the same canvas to the same project is an
-- update of the existing share, never a second row nobody can tell apart.
create unique index if not exists shared_canvases_source_target_key
  on app.shared_canvases (source_canvas_id, scope, target_id) where revoked_at is null;

alter table app.shared_canvases enable row level security;
alter table app.shared_canvases force row level security;

drop policy if exists shared_canvases_read on app.shared_canvases;
create policy shared_canvases_read on app.shared_canvases for select
  using (department_id = app.current_department_id());

drop policy if exists shared_canvases_write on app.shared_canvases;
create policy shared_canvases_write on app.shared_canvases for all
  using (department_id = app.current_department_id() and not app.is_view_as())
  with check (department_id = app.current_department_id() and not app.is_view_as());

-- --------------------------------------------------------------------------------------------------
-- 2. Calendar feeds (SPEC §10 "per-user secret ICS feeds ... regenerate/revoke").
--
-- `secret` is a bearer capability, exactly like `app.sessions.id`: a calendar app subscribes once by
-- URL and carries no cookie afterwards, so the URL itself has to be the credential. It is 32 bytes of
-- CSPRNG output (base64url, generated by the API), it is revocable and regenerable per feed, and it
-- grants exactly one thing: read-only ICS for the one user it belongs to.
--
-- **Why this table carries no RLS policy**, and why that is the same decision the codebase already
-- made twice: a feed secret has to be turned into a user id *before* any user context exists to
-- satisfy a policy -- identical to `app.sessions` ("looked up by token before you know who is
-- asking") and to `app.telegram_links` ("a webhook update carries only a chat id"). Both are
-- classified `global` in `packages/db/src/tenancy.ts` with exactly that reason, and per-user
-- visibility for both is enforced in the application layer by `can()` plus an explicit
-- `user_id = <the caller>` predicate on every authenticated query -- which is what
-- `modules/calendar/repo.ts` does here too. A `security definer` function was the other candidate and
-- does NOT work: `devon_migrator` owns every table and every table is `force row level security`, so
-- a function it owns is bound by the same policies its caller would have been.
do $$ begin
  create type app.calendar_feed_kind as enum ('all', 'events', 'tasks');
exception when duplicate_object then null;
end $$;

create table if not exists app.calendar_feeds (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references app.users (id),
  kind app.calendar_feed_kind not null default 'all',
  secret text not null unique,
  label text not null default '',
  created_at timestamptz not null default now(),
  rotated_at timestamptz,
  revoked_at timestamptz,
  last_accessed_at timestamptz,
  access_count integer not null default 0
);

create index if not exists calendar_feeds_user_idx on app.calendar_feeds (user_id)
  where revoked_at is null;

-- --------------------------------------------------------------------------------------------------
-- 3. Web push (SPEC §10 "Web push (VAPID) with opt-in in inbox preferences and a service worker").
--
-- One row per browser (per `endpoint`, which is what the push service itself keys on). Owner-only:
-- a subscription is a device of one person, and the head has no business enumerating anyone's
-- devices. The sender runs inside the recipient's own context (`withContext({ userId })`), so the
-- policy holds on the delivery path too.
create table if not exists app.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references app.users (id),
  endpoint text not null unique,
  p256dh text not null,
  auth_secret text not null,
  browser_label text not null default '',
  locale text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_sent_at timestamptz,
  failure_count integer not null default 0,
  disabled_at timestamptz
);

create index if not exists push_subscriptions_user_idx
  on app.push_subscriptions (user_id) where disabled_at is null;

alter table app.push_subscriptions enable row level security;
alter table app.push_subscriptions force row level security;

drop policy if exists push_subscriptions_scope on app.push_subscriptions;
create policy push_subscriptions_scope on app.push_subscriptions for all
  using (user_id = app.current_user_id())
  with check (user_id = app.current_user_id());

-- The instance's VAPID identity: one keypair for the whole box, generated on first use and kept
-- afterwards (rotating it silently unsubscribes every browser). Instance-wide configuration, like
-- `app.instance_settings` -- no department, no user, no RLS. `VAPID_PUBLIC_KEY`/`VAPID_PRIVATE_KEY`
-- in the environment win over this table when both are set, so an operator who wants to manage the
-- keypair outside the database still can (docs/ops/REALTIME-CALENDAR.md).
create table if not exists app.push_vapid_keys (
  id text primary key default 'default',
  public_key text not null,
  private_key text not null,
  created_at timestamptz not null default now()
);

reset role;
